### ISSUE TITLE
SDK test view not working (when local)?

### ISSUE THREAD

**Issue by cgreenhalgh** [me-box/databox#106]
Running databox with (local) sdk, i can make a simple app but don't see any events in the debug view or any output in the app view: [https://github.com/cgreenhalgh/databox.databox-sdk-app-1](https://github.com/cgreenhalgh/databox.databox-sdk-app-1)

But equally I'm not sure what components are supported by the test view...

**Comment by tlodge** [comment]
should be ok, suspect that there were no outputs to see - if you hook the debug node directly to the osmonitor datasource you should see something when you click on the debug output.   The chart node needed an update, it should now give you the option of what data to plot;  after that you should see something when you click on the app output.

**Comment by Toshbrown** [comment]
"Should be ok" is good enough for me closing ;-)
