### ISSUE TITLE
SDK missing documentation, including smoke test guide

### ISSUE THREAD

**Issue by cgreenhalgh** [me-box/databox#107]
Using the SDK I don't know what components *should* work in the test or app view.

E.g. a simple set of instructions that would make a "known good" app with some indication of what "success" should look like, both test and on databox would be great.

**Comment by tlodge** [comment]
Yes - documentation/tutorials being added at:  http://tutorial.iotdatabox.com/ and this will include clear instructions on how to test/what can be tested.  In addition the sdk will come with a bunch of example apps that can be used to get started.

**Comment by Toshbrown** [comment]
@tlodge can you close this now you are assigned to it? (don't close it if it's not done)

**Comment by tlodge** [comment]
nope!

**Comment by Toshbrown** [comment]
Done see http://tutorial.iotdatabox.com/#

@tlodge 👍 💯
