### ISSUE TITLE
android app app store list/info doesn't update consistently

### ISSUE THREAD

**Issue by cgreenhalgh** [me-box/databox#109]
@ktg - when using the databox app (version 0.2.1) if I am using the app (with a dev install) then publish a new app (using the SDK in this case) the app store list doesn't update to show it. 
Similarly republished an existing app, changing the input (i.e. manifest info), and the app still showed the old manifest/source information.
After force stop the new information was shown. But there doesn't seem to be any reload-type option within the app.

**Comment by Toshbrown** [comment]
@cgreenhalgh This worked for me in testing after the merge. Closing (open another issue if it's still a problem for you).
