### ISSUE TITLE
What is the best way to log/manage issues?

### ISSUE THREAD

**Issue by cgreenhalgh** [me-box/databox#111]
I think the permissions on this repo mean that very few people can tag issues or close them. 
But if we put issues against individual repos then it is hard to keep track of them, and I'm not sure how that plays now with the PR model...

**Comment by toshtest** [comment]
Just created a test amount to see what none team members can do.

**Comment by toshtest** [comment]
Looks like if i own it then i can close it see https://github.com/me-box/databox/issues/112

**Comment by Toshbrown** [comment]
I'm happy to triage incoming issues tag and assign them and keep on top of closing out resolved ones. 

I'd like to keep all issues on the databox repo, but people open issues on other components then they can refer to the ones hear to give a central monitoring point. This has worked well in the past.
