### ISSUE TITLE
hue bulbs driver

### ISSUE THREAD

**Issue by tlodge** [me-box/databox#114]
Doing a hue bulb test with a new sdk [app](https://github.com/tlodge/databox.tutorial-on-off) which should flash a hue bulb on/off every second.  I'm seeing following with driver-phillips-hue-store-json:

[WS] Sending data
[WS] Not sending data WS not open
[WS] Sending data
[WS] Not sending data WS not open
[WS] Sending data
[WS] Not sending data WS not open

and  driver-phillips-hue shows the following:

192.168.1.109
[HUE.findHub] 192.168.1.109
[findHub] new settings saved
res.render('config', {})
[SETTINGS] retrieved { user: 'databox',
  hash: 'L-Wcj7ta2jQTAhx9gjR9YOOB7rmx8xjac4a5xYWu',
  hostname: '192.168.1.109' }
[getSettings] { user: 'databox',
  hash: 'L-Wcj7ta2jQTAhx9gjR9YOOB7rmx8xjac4a5xYWu',
  hostname: '192.168.1.109' }
(node:22) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 33): TypeError: actuationEmitter.on(...).catch is not a function
(node:22) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[NEW BULB FOUND] 1 Hue color lamp 1

**Comment by Toshbrown** [comment]
I will take look.

**Comment by Toshbrown** [comment]
fixed
