### ISSUE TITLE
No non-CLI way to get IP of databox when starting app

### ISSUE THREAD

**Issue by cgreenhalgh** [me-box/databox#117]
The app needs the IP address of the databox (assuming it doesn't discover it, which it generally won't at the moment) but there's no easy way to get it.
Of course the databox should really do the QR code/URL with single-use token thing (on start-up, or via localhost-only view) so that there is also some element of security, and that would fix the issue...

**Comment by Toshbrown** [comment]
Should be easy enough to pass the IP external IP to the container manager databox-start [L61](https://github.com/me-box/databox/blob/master/databox-start#L61) has the right information. 

This will not work in the case where databox is installed within a full Linux VM but should work in most other cases.

**Comment by Toshbrown** [comment]
This could be fixed along with #136

**Comment by Toshbrown** [comment]
Fixed in v0.3.0
