### ISSUE TITLE
Is there device id and data id ?

### ISSUE THREAD

**Issue by tsh-box** [me-box/databox#118]
Hello,
After installed the driver and app,IOT data id (for example;device id or data id ) are also recorded in db??

**Comment by jptmoore** [comment]
Hi.

As part of the REST api you specify the id/key in url path which is used to store/retrieve blobs of JSON. Within the JSON blob you can design your own structure with device specific IDs etc.

**Comment by tsh-box** [comment]
Thank you for reply :) ,
If possible,Please Could you explain the difference between of 
1. SLA
2.Store-json
3.Time series
4.Store-json-blob

**Comment by jptmoore** [comment]
re: 1: when you install an app/driver you are presented with information on what the app/driver does or needs to do to run in a similar way to when you install mobile apps from an app store.

re: 2-4: we are working on supporting different types of data stores depending on driver/app requirements. Currently you can store JSON, or JPEGs depending on the store.
