### ISSUE TITLE
databox dashboard ui

### ISSUE THREAD

**Issue by tlodge** [me-box/databox#121]
When a user clicks on the icon to uninstall an app, it's not clear that request has worked.  It can appear as though either nothing is happening or that the user has accidentally clicked the refresh icon next to it.  Would be nice to give some indication that the box is in the process of uninstalling the app.

**Comment by Toshbrown** [comment]
👍  I second this proposal 

@ktg can you make it happen?

**Comment by ktg** [comment]
I'll investigate this next week and let you know
