### ISSUE TITLE
android mobile app sensingkit

### ISSUE THREAD

**Issue by tlodge** [me-box/databox#123]
Running it on a nexus 7, seems as though I can only get readings for the light sensor - other sensors (such as audio-level) do not appear to work, where they have before with previous standalone sensingkit app.

**Comment by haddadi** [comment]
also adding Yousef in case he has noticed any changes

**Comment by tlodge** [comment]
should be ok now, was issue with the app

**Comment by haddadi** [comment]
from @minoskt

I strongly advise to use the dev brunch for the Android SensingKit as it includes far more sensor support and some new (a bit untested) features.

I think the issue  is related to updated permission in new Android. I want to make this part easier in SensingKit but just don't have enough free time at the moment.
