### ISSUE TITLE
databox dashboard sensingkit dies

### ISSUE THREAD

**Issue by tlodge** [me-box/databox#129]
After a period of time, sensingkit appears to stop working (apps no longer receive data from any of the sensors), and a re-install of the sensingkit driver is needed.  The driver-sensingkit-store-json does appear to still be sending data (seeing lots of [WS] Sending data logs).  The driver-sensingkit is still showing logs for toggling the sensors, but also a large number of the following messages:

```
 (node:17) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 21107): TypeError: cb is not a function
```

**Comment by Toshbrown** [comment]
@yousefamar is this something you would have time to take a look at?

**Comment by haddadi** [comment]
I'm guessing this is a token/arbiter issue, but just in case also adding @minoskt

**Comment by yousefamar** [comment]
Trying to recreate this now; not quite sure where in the pipeline it could be happening (might be easier to debug over chat).

- How long does it take before this starts happening? Any chance it could be a memory leak / out of memory issue? Any container involved capping out?
- Is the store definitely receiving data? Can you connect directly to mongo and `.find()`?

The fact that the store seems to be (trying to?) send something means that it must be getting data to send, but then that wouldn't explain why the driver is logging errors and why that issue goes away when you restart the driver (unless the store is also restarted).

The error also doesn't tell me much unfortunately. `cb`, which is more than likely the name of a callback function, is not a name that is used anywhere in `driver-sensingkit` or `node-databox`. So my hunch would be that some call to a library is being made that expects a callback function as an argument, but doesn't get one.

Without a stack trace (which these uncaught rejections don't give) my best guess would be that it must be as a new sensor is being registered as a datasource [here](https://github.com/me-box/driver-sensingkit/blob/master/main.js#L38-L45).

I'm trying to think, what would actually happen if a driver tried to stream data to a store for a datasource key that it did not — or failed to — register? Could the result be this behaviour? And how/why would that be connected with time? Does it stop just randomly or on trying to toggle a new sensor?

Edit: by register I mean add to the store catalogue.
