### ISSUE TITLE
Seed dev mode local registries with images automatically

### ISSUE THREAD

**Issue by yousefamar** [me-box/databox#13]
Currently, when you launch in dev mode, a script is generated that you're told to run manually through `sh ./updateLocalRegistry.sh` in order to pull images from DockerHub and push them to your local registry. It should be possible to skip this step and make the whole process easier by having the CM check what images are missing and automatically populate the local registry through Dockerode/Docker Remote API rather than user + CLI.

**Comment by Toshbrown** [comment]
Agreed, It should only pull if the image is not available. It is a pain if it overwrites an image you are working on ;-)

**Comment by mor1** [comment]
Are those images not tagged locally as `databoxsystems/<image>` though?
And images in that org should be autobuilt thus not dependent on being locally built and pushed.
So how do your in development images get overwritten?
(Though @sevenEng did have some issues with auto-built vs locally built images that I don't think were tracked down...)

**Comment by yousefamar** [comment]
I think Tosh was referring to overwriting in the local registry. The local registry is also separate from local images, in that it's literally a registry instance running locally.

(I was [never fully sold](https://github.com/me-box/databox-app-server/issues/3) on that idea btw, but learned to accept it. :))

**Comment by yousefamar** [comment]
Ah I think I misunderstood. They're pulled from the org, tagged `localhost:5000/databox-component` and pushed to local registry. E.g.

    docker pull databoxsystems/databox-arbiter
    docker tag databoxsystems/databox-arbiter localhost:5000/databox-arbiter
    docker push localhost:5000/databox-arbiter

And that should overwrite locally built containers that you're developing and already pushed to the local registry as far as I'm aware, unless there's a different way to go about it.

**Comment by mor1** [comment]
Ah right, I see. Tags may be used perhaps, though that would require whatever is `pull`ing to know which image is required (and thus require us to decide which should be obtained by default).

Eg., use a tag "dev" if you're developing core components locally?

**Comment by Toshbrown** [comment]
fixed in #24
