### ISSUE TITLE
Container manger UI landing page

### ISSUE THREAD

**Issue by Toshbrown** [me-box/databox#134]
When using the databox mobile app or web UI you are currently dumped into the interface at the app store. This is not very useful for first-time users. Could we add a landing page to help them get started?  

## Proposed text 

**Welcome to databox** 

Databox lets you take control of your personal data and IoT devices. 

Get started by: 

Install the _sensing kit driver_. This will allow databox to access the sensors on this mobile phone. This driver is used by some of the demo apps. 

Install a driver from the [driver store](/#!/driver/store). 

Install an app from the [app store](/#!/app/store).

For more help see the [documentation](https://github.com/me-box/databox)

**Comment by Toshbrown** [comment]
Fixed in https://github.com/core-container-manager/pull/8

**Comment by haddadi** [comment]
would be great to have the logo too.. but not citical
