### ISSUE TITLE
user interface is not secured

### ISSUE THREAD

**Issue by cgreenhalgh** [me-box/databox#136]
The browser and app interfaces have no client authentication, so any device with physical network access to a databox can do anything that the interface supports (install/start/stop drivers/apps, etc.).

Some (simple) options:
- ensure that API is only accessible over HTTPS
- enable basic authentication for the API and proxy access to container UIs
- (a) databox installation generates a password and prints on the console or
- (b) uses default password, but first user is prompted to change it

Note: will need specific support in the app as well as the browser UI

There is also suggestion for the app (currently unimplemented) of using a QR code to do initial configuration, presumably by embedding the password (or another shared secret) in the code (fragment?). If the QR code also has the IP then this also fixes the discovery issue (at least locally). Assuming the code/URL is locally generated then it needs to be obtained from a (relatively) secure channel, e.g. printed in the console, or served only to a localhost browser.

**Comment by cgreenhalgh** [comment]
It look like UI is currently always access over HTTP (as per the console output after starting, but contra the README.md). I'm not at all sure how HTTPS would be set up (in terms of certificates) for a databox with a local and possibly dynamic IP address...

**Comment by cgreenhalgh** [comment]
So one approach seems to be to install the databox's self-signed root certificate on the device that will access the databox. There is a bootstrap issue about how you get it and why you trust it, but there always is... and possibly on some devices ability to install new CAs might be locked down??

The databox CA cert might be installed in the OS, or only in the app (if you are using the app). Custom HTTPS certificate handling appears to be possible in iOS and Android (untested).

The databox HTTPS server then need to have keys/certificates for the name/IP by which it is accessed signed with that root key. This is complicated by IP potentially being dynamic (DHCP, moving networks at least for dev), private, and potentially accessed by port forwarding from another public IP. The latter at least (forwarding) would need some manual configuration of the databox with that IP. Dynamic suggests boot-time or run-time generation of key/cert. Hopefully private IP will be OK in a certificate, although CAs won't issue them.

Client authentication can then be basic auth or something else plus cookies/other header tokens.

**Comment by tur-ium** [comment]
Please encrypt the data as well!
I don't want other people on my LAN being able to access the temperature log for my room!

**Comment by mor1** [comment]
@tur-ium Yes, that's something we know we need to add to the store infrastructure :) There's a rewrite of the store component taking place at the moment-- encryption at rest should be added at some point, though right now, we're still trying to get the APIs sorted out so that other parts can make progress. 

In case it isn't clear-- Databox shouldn't be thought of as ready for production yet! Definitely an early-stage prototype still (though hopefully getting to the point where it's possible to develop against it).

**Comment by Toshbrown** [comment]
Https will be addressed in v0.3.0 see PR https://github.com/me-box/databox/pull/207

**Comment by Toshbrown** [comment]
released in 0.4.0

**Comment by mor1** [comment]
@Toshbrown Is this done now? Can the issue be closed?

**Comment by Toshbrown** [comment]
"Toshbrown closed this 17 days ago" ???

**Comment by mor1** [comment]
Hm, thought I refreshed the tab but didn't see it as closed! Never mind
then :)
