### ISSUE TITLE
Proposal: Versioning and release process

### ISSUE THREAD

**Issue by Toshbrown** [me-box/databox#137]
Relates to #6

## Problem 
Currently, the release process is undefined. Releasing a build of Databox is complex as it spans many repositories and also uses several prebuilt Docker images from https://hub.docker.com/r/databoxsystems/. 

## Proposed solution 

Create a tool to manage the release process. This will:

 - Look at the tags on the main databox repo and calculate the next version using semvar (Major, Minor, Patch)
 - Collate All PR into a changelog    
- Present a List of proposed changes so that the user can double check and cancel if necessary
- If the user agrees   
   - Tag all core components with the new version using the GitHub API (triggering docker hub builds tag with :[version])
   - Create/Update the Version file in the main databox repo 
   - Create the release using the GitHub API with the generated changelog 

Once the tool has been created databox-start will need to be altered to: 

 - In normal mode
    - Read the Version file
    - use this version to pull the correct core components

**Comment by Toshbrown** [comment]
The output of the command will look somthing like this
```
nextVersion :: 0.1.3
currentVersion :: 0.1.2
--------------------------------------------------
The Folowing repos will also be tagged with 0.1.3
--------------------------------------------------
```
me-box/databox
me-box/core-container-manager
me-box/core-arbiter
me-box/core-export-service
me-box/store-json
me-box/store-timeseries
me-box/lib-node-databox
me-box/lib-go-databox
me-box/app-os-monitor
me-box/driver-os-monitor
me-box/driver-sensingkit

```
---------------------
Proposed Release Text
---------------------
```
# Changes since last version:
 ## Changes to me-box/databox:
   - 131 dev build changes issue me-box/databox/pull/132
   - small edit of the docker-databox-sdk.yaml for mock datasource issue me-box/databox/pull/130
   - Updated Databox readme issue me-box/databox/pull/127
   - databox-pin issue me-box/databox/pull/115
   - Add Update main databox repo documentation  issue me-box/databox/pull/113
   - Create LICENSE issue me-box/databox/pull/105
   - Fix app store start up for sdk issue me-box/databox/pull/101
   - Allow pinning of repo and branch for testing issue me-box/databox/pull/100
   - Fix/missing appserver issue me-box/databox/pull/96
   - Implement basic integration test issue me-box/databox/pull/94
   - databox: edit pass over README issue me-box/databox/pull/93
   - compose: tidy up .yaml files issue me-box/databox/pull/92
   - Organise scripts issue me-box/databox/pull/91
   - SDK and Tp-link drivers  issue me-box/databox/pull/90
   - Development issue me-box/databox/pull/84
   - Add app-os-monitor issue me-box/databox/pull/72
   - Fix secret naming issue me-box/databox/pull/70
   - HTTPS certs in pem format issue me-box/databox/pull/69
   - Fet/pem issue me-box/databox/pull/68
   - Ask for an IP if more than one is found issue me-box/databox/pull/62
   - Fix for App-store connection error issue me-box/databox/pull/61
   - Repo reorganisation issue me-box/databox/pull/53
   - Fix git cloning when not logged in to GitHub issue me-box/databox/pull/48
 # Changes to core repositories:
 ## Changes to me-box/core-container-manager:
   - Fix version select + add welcome page issue me-box/core-container-manager/pull/8
   - Update README.md issue me-box/core-container-manager/pull/7
   - Fix for me-box/databox#120 issue me-box/core-container-manager/pull/6
   - Remove outdated information from the readme issue me-box/core-container-manager/pull/5
   - Fix me-box/databox#103 and me-box/databox#109 issue me-box/core-container-manager/pull/4
   - use only hostname as route target for export service issue me-box/core-container-manager/pull/3
   - Add a pem formatted https certificate DNM issue me-box/core-container-manager/pull/2
 ## Changes to me-box/core-arbiter:
   - Readme-updated issue me-box/core-arbiter/pull/34
   - Remove base64 encoding of store secrets issue me-box/core-arbiter/pull/33
   - Undo breaking bugfix and honour suggested secret length issue me-box/core-arbiter/pull/31
   - using string-based secrets for easier debugging and help with issue v… issue me-box/core-arbiter/pull/30
   - Add a pem formatted https certificate DNM  issue me-box/core-arbiter/pull/29
   - Fet/swarm issue me-box/core-arbiter/pull/28
 ## Changes to me-box/core-export-service:
   - using multi-stage build issue me-box/core-export-service/pull/27
   - fix token secret en-/de-coding issue me-box/core-export-service/pull/26
   - get https cert/key using PEM file issue me-box/core-export-service/pull/24
   - Update name issue me-box/core-export-service/pull/22
 ## Changes to me-box/store-json:
   - Fix for secret encoding issue me-box/store-json/pull/6
   - Add a pem formatted https certificate DNM issue me-box/store-json/pull/4
   - Renaming and clean up unused files issue me-box/store-json/pull/2
 ## Changes to me-box/store-timeseries:
 ## Changes to me-box/lib-node-databox:
   - rejects when status code not 2XX issue me-box/lib-node-databox/pull/24
   - Readme updated issue me-box/lib-node-databox/pull/23
   - Add a pem formatted https certificate DNM issue me-box/lib-node-databox/pull/22
   - updated app name and data-store issue me-box/lib-node-databox/pull/21
 ## Changes to me-box/lib-go-databox:
```
--------------------------------------------------
Do you want to publish the release above? [no/yes]
--------------------------------------------------
```

**Comment by haddadi** [comment]
Looks awesome! Does it assume travis successfully built already?

**Comment by Toshbrown** [comment]
yeah, Travis should run when the PRs opened/merged if it fails then we don't merge. This tool won't do any merging ;-)

**Comment by Toshbrown** [comment]
The code is done see https://github.com/Toshbrown/GHR

I will integrate with databox after fixing some other bugs first

**Comment by haddadi** [comment]
excellent! cheers Tosh

==
Hamed        https://haddadi.github.io <http://www.eecs.qmul.ac.uk/~hamed/>
