### ISSUE TITLE
timeseries API doesn't allow write for non-current time

### ISSUE THREAD

**Issue by cgreenhalgh** [me-box/databox#138]
The timeseries API/store currently appears to allow only a write of data to be (internally) associated with the current time in the store. The time that the store associates with a data item also doesn't appear to be externally accessible (it is just used internally for time-based filtering), although you could work around that by including the timestamp explicitly in the stored value.

I want to import (historical) time-series data from an external service so I need to explicitly provide the timestamp for each data item (i.e. when it actually happened, as recorded in the external service).

This could be done either by changing/extending the API (at least write, to allow an explicit time) or by specifying/requiring a standard partial structure for the stored values, i.e. an explicit timestamp field, to be used internally as the timestamp.
Proposal:

POST to `<id>/ts/at/<time>/` with value/data as body.

Most general probably allows multiple values per time, but presumably order of values for same time is arbitrary.

(and what about bulk import - that would need a custom datatype of array of objects with TS and value)

**Comment by Toshbrown** [comment]
store-json supports this https://github.com/me-box/store-json/blob/master/src/timeseries.js#L128

If a timestamp is present in `req.body.data.timestamp` it uses that rather than the internal one. 

Which store are you using?

**Comment by cgreenhalgh** [comment]
Hmm, actually the above is true of the [timeseries store](https://github.com/me-box/store-timeseries), but not of the [json store](https://github.com/me-box/store-json).

The json store behaviour, which is only partially documented, uses a `timestamp` field if present in the value, else a `timestamp` field if present in the submitted object/wrapper, else current time.

The json store also returns wrapper objects including `data` and `timestamp`, which can optionally be provided, but i think the timeseries store just stores and returns unchanged (uninspected) values.

So maybe this is actually a documentation and consistency of implementation issue.

**Comment by cgreenhalgh** [comment]
For some reason I thought I should use the `store-timeseries` to store a timeseries :-)

**Comment by Toshbrown** [comment]
That not a bad assumption TBH. Eventually, they will all be replaced by one store to rule them all so it won't be a problem :-)

**Comment by Toshbrown** [comment]
closing due to the impending arrival of the core-store, with it new improved APIs!
