### ISSUE TITLE
databox-install-component is not pulling in changes after the first install

### ISSUE THREAD

**Issue by Toshbrown** [me-box/databox#140]
Once you have installed a component running databox-install-component again does not do a git pull to update the component source.

**Comment by pooyadav** [comment]
I did a  bit of test on this today - i installed a component ->it fetched code from git -and installed. Then I deleted the component directory from local databox directoy and restarted databox. It showed component is already installed. However, I couldn't see the local directory or any pulling from git. How it saves this status even after i stop databox and restart again.
