### ISSUE TITLE
When deleting an app or driver from the UI dependent store are not removed which cause errors on reinstall

### ISSUE THREAD

**Issue by Toshbrown** [me-box/databox#141]
This cause errors and warning on the next install

**Comment by sevenEng** [comment]
About this, I'm also wondering about what should be done with the dependent stores when app/driver is uninstalled, cause this influence the bridge in how to deal with the dedicated network created for them and the related states/configurations in bridge.

Should I assume the dependent stores will also be removed together with the app/driver? Or they will be left around in case user reinstall app/driver?

**Comment by Toshbrown** [comment]
I think at the moment that stores should be left. 

If an app/driver is reinstalled the store can be reused. 

Deleting a store should be a specific user-driven action with warnings about affected apps and drivers.

**Comment by yousefamar** [comment]
(relevant: https://github.com/me-box/core-arbiter/issues/25)

**Comment by Toshbrown** [comment]
Will be resolve with #169

**Comment by Toshbrown** [comment]
duplicate of  #169 closing
