### ISSUE TITLE
app light graph no datasources found

### ISSUE THREAD

**Issue by tsh-box** [me-box/databox#152]
hello,

I built the Databox UI with the latest version in window10.
I installed the driver-sensingkit on Databox app of android os.After installing,I selected the mobile sensor data 

![ccc2](https://user-images.githubusercontent.com/29420329/31642758-a25ff9f4-b327-11e7-9f00-7fe8f6928222.png)

And then I installed the light-graph app ,but I cannot select the datasources 

![con3](https://user-images.githubusercontent.com/29420329/31642863-55d01faa-b328-11e7-980b-ab9db57ec1ff.png)

**Comment by tsh-box** [comment]
Hello,
Please I want to confirm about the light graph,but I cannot proceed because of the sensingkit driver 
only show the following 

![con1](https://user-images.githubusercontent.com/29420329/31873837-b76d5e3a-b800-11e7-97f5-acef82418aed.png)

**Comment by Toshbrown** [comment]
Using sensing kit requires you to install the new app.

**Comment by tsh-box** [comment]
What is the new app name?

**Comment by tsh-box** [comment]
When I clicked the Google Play button ,it opened the Databox app .

**Comment by Toshbrown** [comment]
There are some install instructions here

http://tutorial.iotdatabox.com/gettingstarted/dashboard/

**Comment by tsh-box** [comment]
Thanks you very much :)

**Comment by tsh-box** [comment]
I could not get datastores for light data,So I could not install light graph app.
I think may be something require for network configuration.
