### ISSUE TITLE
what is the purpose of the selection menu to install

### ISSUE THREAD

**Issue by tsh-box** [me-box/databox#156]
When driver installation in Databox container ,what is the purpose of the selection menu to install

![con2](https://user-images.githubusercontent.com/29420329/31698142-d24269f2-b3f6-11e7-85d9-6e966831a259.png)

**Comment by Toshbrown** [comment]
This lets you chose whether to use a local image (that you have built) or one that is pre-built by us. 

It is part of the new development workflow that allows app and drivers to be developed without running in dev mode. 

From now on dev mode is only needed if you want to work on databoxes core components.  

There will be some new documentation coming soon.

**Comment by tsh-box** [comment]
If I want to modify the app (user components) in local,how can I modify ?

**Comment by Toshbrown** [comment]
Sorry this prosess has recently changed: 

## Developing apps and drivers without the SDK

It is possible to develop Databox apps and driver without the SDK. Currently, [Python](https://github.com/me-box/lib-python-databox), [Golang](https://github.com/me-box/lib-go-databox) and [NodeJs](https://github.com/me-box/node-databox) all have support libraries. Building outside the SDK allows you to make smaller more efficient containers and use more third-party libraries.

Developing apps and drivers 'does not' require data box to be started in dev mode.

To get started all you need is a Dockerfile and a databox-manifest.json examples can be found in the libraries '/samples' directories. To make your app available to install locally on your databox you will need to upload the manifest to http://127.0.0.1:8181 and use `docker build -t [your-app-name] .`. Once the manifest is uploaded and the image has built then you should be up to install the app on your local Databox.

If you would like to modify one of the currently available actual drivers you can do so by doing the following:
```
./databox-install-component driver-os-monitor
```

This will download and build the code on your machine and upload the Databox manifest to your local app store. You can also use this with your repositories and forks using:
```
./databox-install-component [GITHUB_USERNAME]/[GITHUB_REPONAME]
```

**Comment by tsh-box** [comment]
Hello,
In previous version,
I could built with dev mode and then when I  installed app or driver,the source code are also downloaded into the local server,and I have modified the app or driver .
In latest version,
 I have run in dev mode ,but driver-sensingkit's source code cannot downloaded into the local server.
So I cannot modify the app or driver.

**Comment by Toshbrown** [comment]
run `./databox-install-component driver-sensingkit` so install the src and build the image for local install. Once you have made the modifications you can run `./databox-install-component driver-sensingkit` to rebuild and reinstall.
