### ISSUE TITLE
What kind of information from twitter in the app twitter 

### ISSUE THREAD

**Issue by tsh-box** [me-box/databox#157]
Hi!
The twitter app accepted data from twitter.
Please could you tell me, this is what kind of information?

![con7](https://user-images.githubusercontent.com/29420329/31704328-b540cf22-b41b-11e7-8693-60632ae024e7.png)

**Comment by Toshbrown** [comment]
Its the last tweet received, with the output of a very simple sentiment analysis (https://www.npmjs.com/package/sentiment)
