### ISSUE TITLE
Time-series store build failed when  ./databox-start dev

### ISSUE THREAD

**Issue by pooyadav** [me-box/databox#158]
It works fine when ./databox-start  but failed when  ./databox-start dev
See error below.
Starting build store-timeseries ...
The command '/bin/sh -c sudo apk add --no-cache --virtual .build-deps alpine-sdk bash ncurses-dev m4 perl gmp-dev zlib-dev libsodium-dev opam && opam init && opam pin add -n opium https://github.com/me-box/opium.git#fix-ssl-option && opam pin add -n sodium https://github.com/me-box/ocaml-sodium.git#with_auth_hmac256 && opam install -y core lwt tls sodium macaroons opium cohttp ezirmin bos && sudo chmod +x build.sh && sync && ./build.sh && rm -rf /home/databox/.opam && sudo apk del .build-deps && sudo apk add libsodium gmp zlib' returned a non-zero code: 4
[2017-10-18T10:44:32+0100 databox-start]: Build store-timeseries 
ERROR: 4 FAILED

**Comment by Toshbrown** [comment]
@jptmoore can you take a look at this, please? It effects databox-install-components

@pooyadav you can get around this for now by removing these lines https://github.com/me-box/databox/blob/master/databox-install-component#L71

Also if you are doing app/driver development you don't need to run in dev mode anymore.

**Comment by pooyadav** [comment]
Yes, I don't need dev mode just to build a driver - so this is not stopping  my work.

**Comment by Toshbrown** [comment]
Fixed in https://github.com/me-box/store-timeseries/commit/69c6a2b3de08a358c06ffaec9111071b8eeaf998
