### ISSUE TITLE
The latest source code cannot build successfully in dev mode

### ISSUE THREAD

**Issue by tsh-box** [me-box/databox#160]
Hi ,
I used the latest code and built with dev mode ,
the error occured

![err1](https://user-images.githubusercontent.com/29420329/31750216-8fe3d546-b4b9-11e7-88fc-cb0757754d76.png)

**Comment by Toshbrown** [comment]
You have run out of disk space. See lines above where you have hilighted

**Comment by Toshbrown** [comment]
You have run out of disk space. See lines above where you have hilighted
