### ISSUE TITLE
The latest source code built with dev mode but error occurs

### ISSUE THREAD

**Issue by tsh-box** [me-box/databox#162]
Hi,
I used the latest source code and built with dev mode,
the following error occured

![err2](https://user-images.githubusercontent.com/29420329/31802952-e7084b2c-b58b-11e7-8429-cccd9d95b108.png)

**Comment by jptmoore** [comment]
Hi, can you trying rebuilding please and if it fails can you scroll up the output and look for any specific error message you notice. You can build the image separately by cloning the repo and building through docker:

git clone https://github.com/me-box/store-timeseries
cd store-timeseries
docker build -t store-timeseries .
