### ISSUE TITLE
Could I remove the -- fork option 

### ISSUE THREAD

**Issue by tsh-box** [me-box/databox#163]
Hello,

I tried to login into the running container (driver-os-monitor-store-json) ,so I run following command;
docker exec -i -t driver-os-monitor-store-json.1.vjnj27ux65bpcnegi2bfxkmxu npm start

> store-json@1.0.0 prestart /
> mongod --dbpath database --fork --logpath /dev/null --wiredTigerEngineConfigString="cache_size=50M" 

2017-10-20T04:42:15.730+0000 I STORAGE  [main] Engine custom option: cache_size=50M
about to fork child process, waiting until server is ready for connections.
forked process: 145
ERROR: child process failed, exited with error number 100
npm ERR! code ELIFECYCLE

Question:  When start the mongod Could I remove the -- fork option from 
  mongod --dbpath database --fork --logpath /dev/null -- wiredTigerEngineConfigString="cache_size=50M"   ??

**Comment by Toshbrown** [comment]
If you want to interact with MongoDB then:  

```docker exec -i -t driver-os-monitor-store-json.1.vjnj27ux65bpcnegi2bfxkmxu sh```

Will get you a shell inside the container where you can use the standard MongoDB command line  tools

**Comment by tsh-box** [comment]
Hello,
I have accessed the container in a shell and how to use MongoDB command line tools?

**Comment by tsh-box** [comment]
Hi,
I can access to the MongoDB :)
Thank you,

**Comment by jptmoore** [comment]
Hi. If your intention is to get data into a store you should look at writing a driver within Databox and using the specific APIs. Accessing any backend this way is not supported. If you describe what you are trying to achieve we might be able to help.

**Comment by tsh-box** [comment]
thanks you all
