### ISSUE TITLE
What kind of data does app-os-monitor receive?

### ISSUE THREAD

**Issue by tsh-box** [me-box/databox#167]
Hello ,
I have installed the app-os monitor driver and app.And then I also confirmed the store(timeseries collection).
The following document is what kind of information?

{ "_id" : ObjectId("59eef1e3fe27380030993cac"), "datasource_id" : "loadavg15", "data" : 0.169921875, "timestamp" : 1508831715835 }

**Comment by Toshbrown** [comment]
load average and Memory consumption

**Comment by tsh-box** [comment]
From current pc?

**Comment by Toshbrown** [comment]
from current pc if run outside vm? or for the VM if inside a VM!

**Comment by tsh-box** [comment]
Host pc or guest pc?

**Comment by Toshbrown** [comment]
Guest if your running in a VM host otherwise :-)

**Comment by tsh-box** [comment]
I understand Thanks you :)
