### ISSUE TITLE
About Databox IP address confirmation

### ISSUE THREAD

**Issue by tsh-box** [me-box/databox#168]
Hello,
When building the databox with ./databox-start,
IP confirmation message occured and select the favourite IP.

![con2](https://user-images.githubusercontent.com/29420329/31935710-7eaa5432-b8ea-11e7-8566-359c89ecf23e.png)

The IP confirmation is just for private network IP?
Could be build by using public IP?

**Comment by tsh-box** [comment]
Hello,
When building the databox with ./databox-start,
IP confirmation message occured and select the favourite IP.

![con2](https://user-images.githubusercontent.com/29420329/31936001-4163c436-b8eb-11e7-862e-083b17bd60bb.png)

The IP confirmation is just for private network IP?
Could be build by using public IP?

**Comment by Toshbrown** [comment]
Thay are the IPs viable to the scripts. If an external ip is not viable then you must be tuning in a vm or behind a router performing NAT. As suggested befor running in a vm with bridged networking is the best option.

**Comment by tsh-box** [comment]
Now I have built Databox in Azure Centos7 Virtual Machine.
In Azure VM, has public IP and  private IP.
But when I built it, there is no IP confirmation message and if built successfully, I could not access http://privateIP:8989

**Comment by tsh-box** [comment]
Now I did it ,
I added the port 8989 in Azure VM :) I could access the Databox.
When I accessed the Databox from android app,the loading time is little slow.
