### ISSUE TITLE
Cannot build with dev mode in Azure VM 

### ISSUE THREAD

**Issue by tsh-box** [me-box/databox#171]
Hi,
I try to build Databox with dev mode in Azure CentOs7 VM, but the following error occured 

![con3](https://user-images.githubusercontent.com/29420329/31984750-9a670b9e-b99d-11e7-86da-70000da6d7eb.png)

**Comment by Toshbrown** [comment]
There is a permission denied error when cloning the code. Check your file permissions.

**Comment by tsh-box** [comment]
How to check the  file permissions for databox?

**Comment by Toshbrown** [comment]
It's not a databox problem. its a Linux file system problem. 

the error you need to investigate is:

```
databox-strat: line 132: ./databox-fetch-components: Permission denied  
```

databox-fetch-components is a shell script that clones the required repositories it's not complex and I'm not sure why it is failing in your case.

```
ls -lah
``` 

should give you some information you need.

**Comment by haddadi** [comment]
For more information see
https://www.linux.com/learn/understanding-linux-file-permissions

**Comment by tsh-box** [comment]
Thanks you all
I did it 
I used chmod a+rwx databox-fetch-components
