### ISSUE TITLE
When built with dev mode does not clone for driver-twitter

### ISSUE THREAD

**Issue by tsh-box** [me-box/databox#172]
Hello,
I built with dev mode,and when installed the driver twitter ,the source code of driver-twitter did not clone to the  local.
But other driver(driver-os-monitor and driver-sensingkit) are cloned to the local.

**Comment by Toshbrown** [comment]
Any errors? what command did you run?

**Comment by tsh-box** [comment]
firstly I built Databox with ./databox-start dev
and then I installed the driver twitter from databox UI.
No,I think there is no error ,but it does not clone to local for driver twitter when I confirmed local.

**Comment by tsh-box** [comment]
After installing the light graph app,it's source code also does not clone to local.

**Comment by Toshbrown** [comment]
If you would like to modify one of the currently available actual drivers you can do so by doing the following:
```
./databox-install-component driver-os-monitor
```

This will download and build the code on your machine and upload the Databox manifest to your local app store. You can also use this with your repositories and forks using:
```
./databox-install-component [GITHUB_USERNAME]/[GITHUB_REPONAME]
```
