### ISSUE TITLE
app os minitor modifying 

### ISSUE THREAD

**Issue by tsh-box** [me-box/databox#174]
Hello!
I have modifying the app-os-monitor by adding new code  in /src/app.go

//Register your data source so apps can find it
	_, err := databox.RegisterDatasource(dataStoreHref, databox.StoreMetadata{
		Description:    "Hello world test data",
		ContentType:    "application/json",
		Vendor:         "databox",
		DataSourceType: "test",
		DataSourceID:   "test",
		StoreType:      "ts",
		IsActuator:     false,
	})
	if err != nil {
		panic(err)
	}
	var dataSourceHref = storeURL + "/test"

And I build with ./databox-start dev
the following error is occured 

![con4](https://user-images.githubusercontent.com/29420329/32042504-bccbb5a6-ba72-11e7-811d-f31307a58866.png)

**Comment by Toshbrown** [comment]
Interesting, do get any errors if you build the docker image manually like this?

```
cd app-os-monitor
docker build -t app-os-monitor .
```

**Comment by tsh-box** [comment]
When I modified it,I have a compile error so error occured.
Now I fixed it.
By the way ,the latest source cannot download the light graph app into local when built with dev mode.
