### ISSUE TITLE
store-json get /ts/since and /ts/range don't work with form-encoded parameters

### ISSUE THREAD

**Issue by cgreenhalgh** [me-box/databox#178]
I'm not getting any values (i.e. i get an empty array, `[]`) back from calls to /ts/since and /ts/range when there are valid values in the store. I wonder if it is because the time parameters are left as strings and not converted to ints before used in the db.find, e.g. [here](https://github.com/me-box/store-json/blob/master/src/timeseries.js#L40), [here](https://github.com/me-box/store-json/blob/master/src/timeseries.js#L55) and [here](https://github.com/me-box/store-json/blob/master/src/timeseries.js#L56).

Also the API [documentation](https://github.com/me-box/store-json) appears to give the incorrect path for range, i.e. `/DATASOURCE/range`, which should be `/DATASOURCE/ts/range`

(I'm using a go driver and the go lib, which I have had to [extend](https://github.com/cgreenhalgh/lib-go-databox/tree/store-json-extras), but the store prints diagnostics on SINCE that convince me that the since value is getting to the store)

**Comment by cgreenhalgh** [comment]
Clarification: it doesn't work if the body is form-encoded. Presumably it does if you send a JSON-encoded body, i.e. an object with the parameters as fields (like the Node.js library). 

In my defence the API documentation doesn't say how it should be encoded and it doesn't throw an error with a form-encoded body.

**Comment by Toshbrown** [comment]
store-json will be replaced by the new store. A discussion on the new API is ongoing hear https://github.com/me-box/databox/issues/184

closing this, in anticipation of the new store.
