### ISSUE TITLE
time type is undefined/inconsistent in store APIs

### ISSUE THREAD

**Issue by cgreenhalgh** [me-box/databox#180]
Although undocumented, store-json appears (through an internal use of Date.time()) to expect timestamp to be ms since Unix epoch. It will probably work with fractions of a ms in provided (double / Number) values.

store-timeseries uses seconds since Unix epoch and does not work with fractions of a second (uses int internally).

**Comment by Toshbrown** [comment]
see my reply here https://github.com/me-box/databox/issues/181

**Comment by Toshbrown** [comment]
store-json will be replaced by the new store. A discussion on the new API is ongoing hear https://github.com/me-box/databox/issues/184

closing this, in anticipation of the new store.
