### ISSUE TITLE
timeseries API is different in store-json and store-timeseries

### ISSUE THREAD

**Issue by cgreenhalgh** [me-box/databox#181]
E.g.
- time-related parameters are passed differently
- units and internal type for time are different
- store-timeseries doesn't handle submitted values in the same way, i.e. for store-json it may be an object containing data:, which may have a timestamp (causes #138)
- store-timeseries just returns an array of values (no timestamps), store-json returns an array of objects with data and timestamp

**Comment by Toshbrown** [comment]
Hi Chirs, 

It's my understanding that the store store-json will be retired and all apps and drivers will use store-timeseries (which will be renamed). We will still leave the ability to have more than one store type for special cases not supported by store-timeseries. 

@jptmoore @mor1 is this your understanding?

**Comment by Toshbrown** [comment]
store-json will be replaced by the new store. A discussion on the new API is ongoing hear https://github.com/me-box/databox/issues/184

closing this, in anticipation of the new store.
