### ISSUE TITLE
The version is not respected for apps and drivers

### ISSUE THREAD

**Issue by Toshbrown** [me-box/databox#183]
Currently, when installing apps and drivers the databox version is not used to pull the correct image. It just pulls latest. Which is handy for development but not for production. 

This could be fixed alongside https://github.com/me-box/databox/issues/59

There is also another related problem that occurs if the Image is not found in the registry. The service will start and no errors are shown to the user but the app/driver is not installed

## Proposal 

All images pulled from databoxsystems (or any remote repo) should respect the version 

Local images (ie ones from the sdk or development) should pull :latest

**Comment by mor1** [comment]
Proposal sounds good. The "release" should indicate specific tagged images. Some kind of `dev-mode` can override this. (Actually, ideally, not just to `:latest` but also to any past version-- debugging may need this.)
