### ISSUE TITLE
Modify source code does not work 

### ISSUE THREAD

**Issue by tsh-box** [me-box/databox#186]
Hello,
I want to develop the app-os-monitor ,and So I built the Databox  with dev mode.
And I installed the driver-os-monitor and app-os these code are cloned in local.
And then I stop the Databox and modified the app-os-monitor (src/app.go) by adding the output code  fmt.Println("Hello LLA ") in go func().

And then I rebuilt with dev mode and installed driver-os-monitor and app-os.
When I confirmed the log of app-os-monitor ,the output cannot found.
Please could you tell me what are needs ?

**Comment by Toshbrown** [comment]
1. Don't stop databox (you only need to restart databox if you want to change a core component)
2. After making your changes re-run  ./databox-install-component app-os-monitor (to rebuild the image and update the manifest)
3. Using the databox UI uninstall and reinstall the app-os-monitor

**Comment by tsh-box** [comment]
OK,I`ll be try.

**Comment by tsh-box** [comment]
Enexceptedly,The following error occured when run ./datbox-start dev .
I have tried many time by environment installation and restart, but error does not change.
Pls explain me,I really don't understand this error.

![con22](https://user-images.githubusercontent.com/29420329/32261376-7e13943e-bf11-11e7-83f3-289246acc2df.png)

**Comment by tsh-box** [comment]
And I have run with  previous version Databox ,the modified source code are not work   :-(

**Comment by tsh-box** [comment]
Why does this error occured? Please Could you teach me the solving method?
![con23](https://user-images.githubusercontent.com/29420329/32310732-e011845e-bfd7-11e7-93c4-0c8bfb8c2697.png)

**Comment by Toshbrown** [comment]
We are seeing this error in out Travis ci builds It looks like the nodeJS docker images have changed. I will take a look.

**Comment by tsh-box** [comment]
Thank you,
Please, Could you tell me the Databox source code that can fix the app or driver?
I have to modify in this week.

**Comment by Toshbrown** [comment]
This has been fixed, it was an issue with a renamed pacage in alpine linux stopping store-json from building.

**Comment by tsh-box** [comment]
Thanks,store-json is ok but still error in driver sensingkit

![con23](https://user-images.githubusercontent.com/29420329/32319072-94ae209c-bffc-11e7-99e8-2a9cd0d406f6.png)

**Comment by Toshbrown** [comment]
seeding manifest? is databox running? 

Whats the output of `docker ps`

**Comment by tsh-box** [comment]
![con23](https://user-images.githubusercontent.com/29420329/32320389-faca98fc-c000-11e7-833d-5a031b368ab1.png)

**Comment by Toshbrown** [comment]
app-server is not running what do u get when you run 

`docker-compose -f ./docker-databox-appstore.yaml up -d`

**Comment by tsh-box** [comment]
I also run docker-compose -f ./docker-databox-appstore.yaml up -d 
How can I solve ?

![to3](https://user-images.githubusercontent.com/29420329/32422567-625ebee0-c2e4-11e7-94d0-d68434993aad.png)

**Comment by Toshbrown** [comment]
The Fail message is telling you that the manifest could not be uploaded. Docker ps showed that the app store was not running. `docker-compose -f ./docker-databox-appstore.yaml up -d` started the app store! 

So just re-run ./databox-install-compent driver-sensingkit

This time it should work.
