### ISSUE TITLE
Store contents do not persist across restarts of docker/host

### ISSUE THREAD

**Issue by cgreenhalgh** [me-box/databox#188]
Although the store-json appears to create and use a volume `database/` this doesn't appear to be maintained across instances of the store service that are created if docker (or the host) are restarted. So after each reboot all stores are empty.

**Comment by Toshbrown** [comment]
I think this is because the container manager mounts the volumes for data in /tmp

This should be an easy fix. I will take a look.

**Comment by Toshbrown** [comment]
Not quite so simple thanks to docker for mac :-(  but think I have a cross-platform solution just testing now

**Comment by Toshbrown** [comment]
@cgreenhalgh if you run in dev mode you will get the new changes and data should persist reboots and restarts 

the main cm will be updated in the next release
