### ISSUE TITLE
Async-ify dashboard requests

### ISSUE THREAD

**Issue by yousefamar** [me-box/databox#19]
<a href="https://github.com/yousefamar"><img src="https://avatars1.githubusercontent.com/u/999235?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [yousefamar](https://github.com/yousefamar)**
_Monday Feb 20, 2017 at 17:11 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_
_Originally opened as https://github.com/me-box/databox-netdev/issues/33_

----

This is not super critical, but just thought I'd make a note of it. (It's also kind of my fault since it's built on shortcuts from the earliest iterations of the CM).

Dashboard requests to the CM are for the most part blocking. One place where this is most noticeable is when installing apps. Now that we use HTTPS everywhere, the CM takes a while to generate certs, and while it's doing that, the dashboard freezes as it waits for a response.

Since we have that Docker event emitter streaming over WS, we might as well have these requests respond immediately, then the Dashboard is free and can wait for a "created" or "started" event to update it's UI. This could be extended to show some sort of "loading" indicator that says what's happening so that the user/dev doesn't think their Databox crashed when it's actually just generating certs.

**Comment by Toshbrown** [comment]
This is fixed in the new UI
