### ISSUE TITLE
Number of networks is limited to ~25

### ISSUE THREAD

**Issue by yousefamar** [me-box/databox#20]
<a href="https://github.com/Toshbrown"><img src="https://avatars1.githubusercontent.com/u/1186363?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Toshbrown](https://github.com/Toshbrown)**
_Thursday Mar 16, 2017 at 16:33 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_
_Originally opened as https://github.com/me-box/databox-netdev/issues/56_

----

Hi all,

Merging #50 and #55  has added a new limitation of approximately 25 networks. This is just about enough for one app/driver/store with the other system components.

Then we get the following error:

     500) server error - could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network

@mor1 @yousefamar @sevenEng Any sugestions?

**Comment by yousefamar** [comment]
<a href="https://github.com/yousefamar"><img src="https://avatars1.githubusercontent.com/u/999235?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [yousefamar](https://github.com/yousefamar)**
_Thursday Mar 16, 2017 at 17:07 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

----

Can confirm, if you run `for i in {1..500}; do docker network create n$i; done` it's about the same. We might be able to overcome this by using the `subnet` flag in when setting up networks, but needs some investigation. More info here: https://github.com/docker/docker/issues/23971#issuecomment-255210570

**Comment by yousefamar** [comment]
<a href="https://github.com/yousefamar"><img src="https://avatars1.githubusercontent.com/u/999235?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [yousefamar](https://github.com/yousefamar)**
_Thursday Mar 16, 2017 at 17:11 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

----

In fact those `--net-cdir=10.1.0.0/8 --net-size=24` seem to be supported too. I think if we set it up so it's not with Docker's default subnet settings, we'll have a lot more space. https://xkcd.com/865/

**Comment by yousefamar** [comment]
<a href="https://github.com/Toshbrown"><img src="https://avatars1.githubusercontent.com/u/1186363?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Toshbrown](https://github.com/Toshbrown)**
_Thursday Mar 16, 2017 at 19:32 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

----

It might have been renamed --fixed-cidr but the docs are a bit vague. Can't see how to set it on MacOS either.

Moving to ipv6 would fix it too, but I think that's asking for trouble.

**Comment by yousefamar** [comment]
<a href="https://github.com/yousefamar"><img src="https://avatars1.githubusercontent.com/u/999235?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [yousefamar](https://github.com/yousefamar)**
_Thursday Mar 16, 2017 at 19:46 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

----

Looking through dockerode unit tests to see if they wrap whatever bit of the Docker Remote API that does that yielded this: https://github.com/apocas/dockerode/blob/be7e3cb81e0725430f515aca4dabfbb357717ef9/test/networks.js#L29

I haven't tested this but perhaps if we create networks with IPAM configs where we have CIDRs that are e.g. `/8`, then in theory it should allow us to have 16,777,216 hosts at a time. We can have it use those class A type IPs too that start 10.0.0.1 instead of Docker's default 172.16.0.1 space (class B?).

**Comment by yousefamar** [comment]
<a href="https://github.com/sevenEng"><img src="https://avatars0.githubusercontent.com/u/5914530?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sevenEng](https://github.com/sevenEng)**
_Friday Mar 17, 2017 at 01:11 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

----

I think using the *IPAM* configs as @yousefamar has mentioned could be a good way to solve this, but I don't think the question is that we don't have enough IP address for the hosts but rather not enough subnet address for the networks. So maybe we could use CIDRs that are `/24` or even longer, to get enough subnet addresses to provision this.

Also, I'm not sure what happened with the Docker's default class B space, as it should definitely provide more subnet addresses than ~25 or ~30. Will take a look into this later.

And I'm investigating into this by using *IPAM*, hope could come up with something later today.

**Comment by Toshbrown** [comment]
@sevenEng can this be closed? I don't think the current version is affected by this.

**Comment by sevenEng** [comment]
Yes, I think so!
