### ISSUE TITLE
Name conflicts with an existing object on reinstall

### ISSUE THREAD

**Issue by aid-oc** [me-box/databox#204]
After uninstalling a driver and updating using databox-install-component, reinstalling the driver through the UI fails until databox is restarted.

databox_container-manager shows (repeats for each secret):

![image](https://user-images.githubusercontent.com/20520093/33329209-f1d42daa-d453-11e7-867a-7f58b3eb5add.png)

The container running the drivers shows:

`[waitForStoreStatus] Retrying in 1s...
{ Error: getaddrinfo ENOTFOUND arbiter arbiter:8080
    at errnoException (dns.js:53:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:95:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'arbiter',
  host: 'arbiter',
  port: '8080' }
`

**Comment by Toshbrown** [comment]
Hi, thanks for the report. 

This is an issue with the core-network not handling restarts properly @sevenEng is looking into it.

**Comment by sevenEng** [comment]
Hi @psyaoc 
thanks for your feedback! Do you maybe still have some logs from databox-network? That'd be really helpful to pin down the problem.

**Comment by Toshbrown** [comment]
The name conflict errors are a known issue https://github.com/me-box/databox/issues/141. However, they don't affect normal operation.  

The main isue here is this: 

> [waitForStoreStatus] Retrying in 1s... { Error: getaddrinfo ENOTFOUND arbiter arbiter:8080 at errnoException (dns.js:53:10) at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:95:26) code: 'ENOTFOUND', errno: 'ENOTFOUND', syscall: 'getaddrinfo', hostname: 'arbiter', host: 'arbiter', port: '8080' }

**Comment by sevenEng** [comment]
Right, I agree on this. But this still seems different from restart situation, as the driver gets removed and then reinstalled, there are snippets in CM to call on core-network to update the policies upon both events. Unless it's also a timeout on name resolving issue, which I just pushed a [commit](https://github.com/me-box/core-network/commit/d30e34c362760f1d8661ff78a2b22978dfce8eec) to deal with, then I may need more input on this. Meanwhile yep, I'm looking into the restart issue.

**Comment by sevenEng** [comment]
Hi @psyaoc, this should have been fixed by the most recent commits on master branch of core-network. If the failure persists, please let us know.

**Comment by aid-oc** [comment]
@sevenEng That's great, thank you. I'll let you know if I encounter any more issues with it.
