### ISSUE TITLE
https access fails due to certificate problem

### ISSUE THREAD

**Issue by cgreenhalgh** [me-box/databox#210]
Using version tag 0.3.0 on Mac OS, after installing the databox certificate and trusting it, I still cannot access the databox secure pages from Chrome or Safari, and can only do so from Firefox by adding an additional security exception.

The error appears to be due to the HTTPS certificate and/or the root certificate not specifying the Organisation and Organisational Unit for the Issuer and/or Issued to.

E.g. Chrome reports "NET::ERR_CERT_INVALID" and "the website sent scrambled credentials that Google Chrome cannot process".

**Comment by Toshbrown** [comment]
Hi, 

What version of MacOS are you running? I was debugging a similar problem earlier with @tlodge.

Accessing his version of databox from my laptop (MacOS High Sierra 10.13.1) did not have the same problem. 

Adding Organisation and Organisational Unit should not be difficult @ktg can you take a look, please.

**Comment by cgreenhalgh** [comment]
Mac OS el capitan 10.11.6.

**Comment by haddadi** [comment]
faced similar issue, proceeded by proceeding with the security exception
only

==
Hamed        https://haddadi.github.io

**Comment by Toshbrown** [comment]
PR #213 Did not fix this problem. Can someone post the output of this? 

```
cd ./certs

openssl verify -verbose -CAfile ./containerManager.crt ./container-manager.pem

openssl version
```

**Comment by haddadi** [comment]
Badger:certs hamed$ openssl verify -verbose -CAfile ./containerManager.crt ./container-manager.pem
Error opening certificate file ./container-manager.pem
140735893091208:error:02001002:system library:fopen:No such file or directory:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-22/libressl/crypto/bio/bss_file.c:255:fopen('./container-manager.pem', 'r')
140735893091208:error:20074002:BIO routines:FILE_CTRL:system lib:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-22/libressl/crypto/bio/bss_file.c:257:
unable to load certificate
Badger:certs hamed$ 
Badger:certs hamed$ openssl version
LibreSSL 2.2.7
Badger:certs hamed$

**Comment by Thomas-Lodge** [comment]
```
openssl verify -verbose -CAfile ./containerManager.crt ./container-manager.pem
./container-manager.pem: OK
tlodge-2:certs tomlodge$
```
```
tlodge-2:certs tomlodge$ openssl version
OpenSSL 0.9.8zh 14 Jan 2016
```

```

**Comment by Toshbrown** [comment]
Fixed in https://github.com/me-box/databox/commit/e2d77c76f50dab2905b9ac47cfadf0275f13c3aa
