### ISSUE TITLE
Local apps/drivers not visible from browser for 0.3.0 due to security issue

### ISSUE THREAD

**Issue by cgreenhalgh** [me-box/databox#211]
Using a browser (Firefox on MacOS) to access the databox, tag 0.3.0, it lists drivers from the public app store, but fails to list drivers in the local app store. 

Firefox shows the following console error 'Blocked loading mixed active content “http://localhost:8181/app/list”'

This appears to be a general security restriction preventing XMLHTTPRequests to non-https URLs from a page served over HTTPS.

To resolve this issue the local app store will also need to use HTTPS and/or be proxied by the container manager HTTPS proxy.

**Comment by cgreenhalgh** [comment]
Just to note for there is a work-around for this in firefox as per [this issue](https://bugzilla.mozilla.org/show_bug.cgi?id=903966): 

> you can also set security.mixed_content.block_active_content as false in about:config. Of course, this affects all the content you load in the browser, not just the localhost stuff, so you will be decreasing security.

**Comment by Toshbrown** [comment]
Once https://github.com/me-box/databox/pull/215 is merged this will work.
