### ISSUE TITLE
ERROR :service endpoint with name databox-arbiter already exists

### ISSUE THREAD

**Issue by yousefamar** [me-box/databox#22]
<a href="https://github.com/Toshbrown"><img src="https://avatars1.githubusercontent.com/u/1186363?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Toshbrown](https://github.com/Toshbrown)**
_Friday Mar 17, 2017 at 08:54 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_
_Originally opened as https://github.com/me-box/databox-netdev/issues/60_

----

When reinstalling an app/driver, or restarting with saved containers, after merging #50 and #54 we get the following error.

Error: (HTTP code 500) server error - service endpoint with name databox-arbiter already exists

**Comment by yousefamar** [comment]
<a href="https://github.com/yousefamar"><img src="https://avatars1.githubusercontent.com/u/999235?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [yousefamar](https://github.com/yousefamar)**
_Friday Mar 17, 2017 at 09:11 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

----

A bit of digging yields this: https://github.com/docker/docker/issues/20398. It seems that this happens either when trying to connect arbiter to a network it is already connected to, or if it's removed before restart, then some sort of bug where it needs to be explicitly disconnected first.

A workaround may be to try and disconnect a container before reconnecting it, or inspecting and seeing if it's connected, but maybe it's an issue where we try to connect it twice so perhaps network inspect and arbiter container inspect networks might unearth what's going wrong?

**Comment by yousefamar** [comment]
<a href="https://github.com/yousefamar"><img src="https://avatars1.githubusercontent.com/u/999235?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [yousefamar](https://github.com/yousefamar)**
_Friday Mar 17, 2017 at 16:43 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

----

It may have been the first case after all, due to a bug in dockerode that @sevenEng hunted down! https://github.com/apocas/dockerode/pull/349

**Comment by yousefamar** [comment]
<a href="https://github.com/yousefamar"><img src="https://avatars1.githubusercontent.com/u/999235?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [yousefamar](https://github.com/yousefamar)**
_Monday Mar 20, 2017 at 18:07 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

----

I think this bug is actually secretly two bugs in one. The first caused by above, the second due to network naming. I have a strong hunch that for some reason you can't have a network be named the same as a container. The places where it fails for me coincide with store names, i.e. `databox-driver-databox-store` as that driver's store's name, collides with the network between that driver and store.

I think I'm very close to cracking #56, but this is holding me back. Will investigate and report back.

**Comment by yousefamar** [comment]
<a href="https://github.com/yousefamar"><img src="https://avatars1.githubusercontent.com/u/999235?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [yousefamar](https://github.com/yousefamar)**
_Monday Mar 20, 2017 at 18:22 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

----

Never mind that; I found out what the problem is. Exactly what I said in my first post:

- C1 wants to connect to C2, and network C1-C2 is made
- C2 wants to connect to C1, and finds that C1-C2 exists, so it tries to take that and turn it into C1-C2-C1-C2
- Hostname collision doesn't let it

https://github.com/me-box/databox/blob/master/src/container-manager.js#L323

PR incoming.

**Comment by Toshbrown** [comment]
This was in the old version with the broken network linking. Closing as it's no longer an issue.
