### ISSUE TITLE
store-json build fail

### ISSUE THREAD

**Issue by ktg** [me-box/databox#221]
From ./databox-start dev:

[2018-01-10 11:44:57 databox-start]: Starting build store-json ...
The command '/bin/sh -c npm install && npm run clean' returned a non-zero code: 127
[2018-01-10 11:44:58 databox-start]: Build store-json 
ERROR: Sending build context to Docker daemon  183.3kB
Step 1/11 : FROM alpine:edge
 ---> 5c4fa780951b
Step 2/11 : RUN echo http://dl-4.alpinelinux.org/alpine/edge/testing >> /etc/apk/repositories && apk add --no-cache mongodb && apk add --no-cache nodejs && rm /usr/bin/mongoperf
 ---> Using cache
 ---> 966f4178ef3c
Step 3/11 : VOLUME /database
 ---> Using cache
 ---> 52b574b6acd0
Step 4/11 : ADD . .
 ---> 9c33080f3f52
Step 5/11 : RUN npm install && npm run clean
 ---> Running in cba60ffe5d12
/bin/sh: npm: not found
 FAILED

**Comment by yousefamar** [comment]
I had this too and wasn't sure if it was just my setup. Temporarily dropped to an older version, but good to know it's not just me. Most likely something going wrong with the `apk add --no-cache nodejs` RUN earlier in the Dockerfile.

**Comment by sevenEng** [comment]
since v3.6, the command `npm` seems to be separated to another package `nodejs-npm`:
https://pkgs.alpinelinux.org/contents?file=npm&path=&name=&branch=&repo=main&arch=x86_64

**Comment by yousefamar** [comment]
Ah, well spotted! Then the fix is just adding a `-npm` on [that line I mentioned](https://github.com/me-box/store-json/blob/master/Dockerfile#L6) and it's irrelevant for ARM.

Edit: or rather installing that package in addition to `nodejs`.
