### ISSUE TITLE
No response from local /app/list over https

### ISSUE THREAD

**Issue by aid-oc** [me-box/databox#222]
Currently unable to see a local driver once the manifest has been uploaded, networking shows no response from https://localhost:8181/app/list as called by the driver store but the same request over http does have a response.

**Comment by Toshbrown** [comment]
Sounds odd the app server was moved to https in v 0.3.1 and it working here. 

Try removing the ./certs dir and restarting databox

are you running in dev mode or in normal mode? 

Whats the version of the app-server image? (docker images | grep databoxsystems)

**Comment by aid-oc** [comment]
Thanks for the reply, the issue has been fixed after deleting my current images and re-starting databox, I must have had some outdated components.
