### ISSUE TITLE
App, Driver and Store persistence

### ISSUE THREAD

**Issue by ghost** [me-box/databox#226]
At the moment, apps drivers and stores do not persist if a machine is rebooted. 

All of these things need to persist when a machine is rebooted / docker restarted. 

This is required for the Living Room of The Future work.

**Comment by Toshbrown** [comment]
This has been re-enabled and tested. Should be included the in the next release or will be available in dev mode once the #228 and https://github.com/me-box/databox/pull/228 have been merged

**Comment by Toshbrown** [comment]
Fixed in 0.3.2
