### ISSUE TITLE
Relay of multicast packets from host network to databox driver

### ISSUE THREAD

**Issue by ghost** [me-box/databox#227]
I need to be able to listen for UDP/SDP multicast packets from the host network for device discovery and sending sensor data.

Can the databox network component be used to forward multicast packets from the external host interface to the drivers?

**Comment by ghost** [comment]
Or an import service would do the job, as suggested here: https://github.com/me-box/databox/issues/45

**Comment by sevenEng** [comment]
at the moment, all the drivers have an interface on the host network, enabling by [this line](https://github.com/me-box/core-container-manager/blob/master/src/lib/databox-network-helper.js#L21)

but I'm thinking maybe should add service discovery support into core-network, or some other system component, to isolate drivers from accessing host network directly

**Comment by Toshbrown** [comment]
I've just tested using tcpdump inside a driver and can confirm that no udp packets are seen when broadcasted over the local network. 

sending udp packets using: 
```
socat -v - udp-datagram:192.168.1.255:8080,broadcast
```

receiving packets on host machine using: 
```
sudo tcpdump -c 4 -l -n -i en7 'udp'
```
works just fine

reciving packets in the driver continer using: 
```
tcpdump -c 4 -l -n -i eth0 'udp and port 8080'
or
tcpdump -c 4 -l -n -i eth1 'udp and port 8080'
```

see nothing. 

The udp broadcasts are not getting past the docker bridge.
