### ISSUE TITLE
what is the purpose of using hub.docker.com that link with databox repositories 

### ISSUE THREAD

**Issue by tsh2** [me-box/databox#244]
hello,

what is the purpose of using hub.docker.com that link with databox repositories?

Sometime build failed.

![ee1](https://user-images.githubusercontent.com/36950432/37501107-26a699f8-2910-11e8-9449-b1a1c7e9cb66.png)

![ee1](https://user-images.githubusercontent.com/36950432/37501291-03fcf180-2911-11e8-8efd-0b89a3a5cae1.png)

**Comment by Toshbrown** [comment]
Not sure I understand your question, hub. docker.com holds pre-built version of all the core components, drivers and apps. If you run databox without the dev flag then the images form docker hub are used.  This means that you don't need to build the images to run databox. 


What are you trying to achieve?

**Comment by tsh2** [comment]
I try to test about the relationship of databox and docker hub.

In build setting,Could I only use the master branch in all the core components?

![www](https://user-images.githubusercontent.com/36950432/37575906-e88fb4ce-2b6c-11e8-9d11-0703e936e42c.png)

**Comment by Toshbrown** [comment]
See here https://docs.docker.com/docker-hub/builds/#create-an-automated-build

under "Create an automated build"
