### ISSUE TITLE
app os

### ISSUE THREAD

**Issue by tsh2** [me-box/databox#254]
hello,

I forked the app-os-monitor to my github account for testing,Recently two new dataresources has appeared,when installing thr app-os.
How to make that I don't use this new datasources ?

Thanks you,

![toco](https://user-images.githubusercontent.com/36950432/39849446-58cabc68-5447-11e8-965e-a91fd6fd3428.png)

**Comment by Toshbrown** [comment]
The new data sources are provided by the new os monitor driver. We released version 0.4.0 recently.

**Comment by tsh2** [comment]
I even used the sourcecode of version 0.2.0 , why did change the app-os-monitor UI and datasources?

**Comment by tsh2** [comment]
There is no way to execute the Databox for Version 0.2.0?

**Comment by Toshbrown** [comment]
git pull the tagged version for the main databox repo https://github.com/me-box/databox/tree/0.2.0
