### ISSUE TITLE
Reinstalling apps and drivers fails unpredictably 

### ISSUE THREAD

**Issue by Toshbrown** [me-box/databox#255]
After some investigation, it looks like sometimes apps are started before the arbiter permissions are configured. In container-manager.js#L208 createService is called before addPermissionsFromSla so if the app starts quickly (the image has already been downloaded) then the app starts before its permissions are granted. This causes errors after an app/driver is reinstalled.

**Comment by haddadi** [comment]
just also adding Yousef in case he can check too to make sure

**Comment by Toshbrown** [comment]
Its an easy fix, I'm happy to do it once I've finished debugging some other issues

**Comment by Toshbrown** [comment]
fixed in https://github.com/me-box/core-container-manager/pull/27
