### ISSUE TITLE
there was no data for os-monitor

### ISSUE THREAD

**Issue by tsh2** [me-box/databox#256]
hello,

I installed the app-os-monitor ,UI can see but there is no data in graph

![tocon1](https://user-images.githubusercontent.com/36950432/39914195-3c750afc-553f-11e8-8100-a1c1b68906c8.png)

And then no export data 

![tocon2](https://user-images.githubusercontent.com/36950432/39914202-4361e48e-553f-11e8-88c1-b8fee8fffbb9.png)

**Comment by Toshbrown** [comment]
did you update the store to 0.4.0 to the APIs have changed? The output of `docker ps` and `docker service ls` would hep me debug the issue.

**Comment by tsh2** [comment]
[vagrant@databox databox]$ docker ps
CONTAINER ID        IMAGE                                      COMMAND             CREATED             STATUS              PORTS                              NAMES
56a99acef2fc        databoxsystems2/app-os-monitor:latest      "./app"             About an hour ago   Up About an hour                                       app-os-monitor.1.pf011hnn437wzokm31c3of4hy
f5174730240f        databoxsystems2/driver-os-monitor:latest   "npm start"         About an hour ago   Up About an hour    8080/tcp                           driver-os-monitor.1.ytdc5ep2ffh62g66q5kz29j78
8cf8dee33382        databoxsystems2/core-store:latest          "./main.exe"        About an hour ago   Up About an hour    5555-5556/tcp                      driver-os-monitor-core-store.1.g6ksqu45nomr5ev30vgn9tmxt
c4c319ae214c        databoxsystems2/export-service:latest      "./service -v"      About an hour ago   Up About an hour    8080/tcp                           databox_export-service.1.ze64fy2cl87vk7em488x2ei23
c9170461970a        databoxsystems2/arbiter:latest             "npm start"         About an hour ago   Up About an hour    8080/tcp                           databox_arbiter.1.ui0ynb0b0p5y1xpk9ex24oi37
bdfcd2e29dd7        databoxsystems2/container-manager:latest   "npm start"         About an hour ago   Up About an hour    8989/tcp                           databox_container-manager.1.x0d8iw6rsk08z6k6wt190nwvi
6829111b725c        databoxsystems2/app-server                 "npm start"         About an hour ago   Up About an hour    8080/tcp, 0.0.0.0:8181->8181/tcp   databox_app-server_1
7af8c7ad21ce        databoxsystems2/core-network:latest        "./start.sh"        About an hour ago   Up About an hour    8080/tcp                           databox_databox-network_1
[vagrant@databox databox]$ docker service ls
ID                  NAME                           MODE                REPLICAS            IMAGE                                      PORTS
wfevjy1qbkuj        app-os-monitor                 replicated          1/1                 databoxsystems2/app-os-monitor:latest
5pc3o5amoeho        databox_arbiter                replicated          1/1                 databoxsystems2/arbiter:latest
hh686n3ovj48        databox_container-manager      replicated          1/1                 databoxsystems2/container-manager:latest   *:80->80/tcp, *:443->443/tcp
g9fzvu3ogov3        databox_export-service         replicated          1/1                 databoxsystems2/export-service:latest
ciejlxdcdvf1        driver-os-monitor              replicated          1/1                 databoxsystems2/driver-os-monitor:latest
lkpaqa5o34ab        driver-os-monitor-core-store   replicated          1/1                 databoxsystems2/core-store:latest
[vagrant@databox databox]$


![333](https://user-images.githubusercontent.com/36950432/39915869-096f5c16-5544-11e8-84ff-c9714c38e45b.png)

**Comment by tsh2** [comment]
core-store should change to 0.4.0?

**Comment by tsh2** [comment]
now data is loaded. Thanks you
