### ISSUE TITLE
UI doesn't show new driver/app - 

### ISSUE THREAD

**Issue by pooyadav** [me-box/databox#257]
Manifest uploaded successfully on https://127.0.0.1:8181/ and image build in non dev mode but doesn't show it in UI. Tried even with ./databox-install-component (no error) still doesn't show the driver and app in local UI.

**Comment by Toshbrown** [comment]
Sorry, I missed this issue. 

First, check the app-server is up-to-date I noticed that it's not updated automatically.
```
docker pull databoxsystems/app-server
```

restart databox the try again. 

You also need to trust the HTTPS root cert for this to work. If you do not the HTTPS request to the app-server from the container manager UI will fail.
