### ISSUE TITLE
twitter driver does not save Twitter Credentuals

### ISSUE THREAD

**Issue by tsh2** [me-box/databox#258]
Hello,

I have installed a twitter driver in databox ,
And i entered the Consumer Key,Consumer Secret,Access Token and  Access Token Secret key ,and clicked save button,
but there was no saved. Why could n't save?

![tocon3](https://user-images.githubusercontent.com/36950432/39980055-d867df4c-5784-11e8-8950-78d310b8d6fd.png)

**Comment by Toshbrown** [comment]
It is hard to debug your problems because you running on a forked version with modification. Try it using databox from the main repo. If it works then its a problem with your modifications. If not let me know and I'll get it fixed.

**Comment by tsh2** [comment]
hello,
I run the databox from main repo ,and installed twitter driver but it also cannot save

![tocon3](https://user-images.githubusercontent.com/36950432/40031651-a8a346be-582b-11e8-9546-96d7e08a3917.png)

**Comment by Toshbrown** [comment]
fixed on 0.5.0
