### ISSUE TITLE
Sometime occured ENOTFOUND in driver and app 

### ISSUE THREAD

**Issue by tsh-box** [me-box/databox#263]
hello,
The following ENOTFOUND error occured when restart the app or driver :(

{"log":"[Proxy] ERROR: /driver-os-monitor/ui getaddrinfo ENOTFOUND driver-os-monitor driver-os-monitor:8080\n","stream":"stdout","time":"2018-05-24T07:04:39.745141735Z"}
{"log":"[Proxy] retry /driver-os-monitor/ui\n","stream":"stdout","time":"2018-05-24T07:04:39.745217037Z"}
{"log":"[databox-request] ExternalRequest https://driver-os-monitor:8080/ui\n","stream":"stdout","time":"2018-05-24T07:04:39.745225937Z"}

**Comment by tsh-box** [comment]
databox_container-manager.1.w1u4qn40mokt@DataboxLae    | [Proxy] ERROR: /app-os-monitor/ui getaddrinfo ENOTFOUND app-os-monitor app-os-monitor:8080
databox_container-manager.1.w1u4qn40mokt@DataboxLae    | [Proxy] retry /app-os-monitor/ui
databox_container-manager.1.w1u4qn40mokt@DataboxLae    | [databox-request] ExternalRequest https://app-os-monitor:8080/ui
databox_container-manager.1.w1u4qn40mokt@DataboxLae    | [Proxy] ERROR: /app-os-monitor/ui getaddrinfo ENOTFOUND app-os-monitor app-os-monitor:8080

Message from syslogd@DataboxLae at May 25 01:35:54 ...
 kernel:unregister_netdevice: waiting for lo to become free. Usage count = 1
databox_container-manager.1.w1u4qn40mokt@DataboxLae    | (node:25) UnhandledPromiseRejectionWarning: Error: connect ETIMEDOUT 10.0.0.3:8080
databox_container-manager.1.w1u4qn40mokt@DataboxLae    |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1161:14)
databox_container-manager.1.w1u4qn40mokt@DataboxLae    | (node:25) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
databox_container-manager.1.w1u4qn40mokt@DataboxLae    | (node:25) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Toshbrown** [comment]
This line looks odd: 

```
kernel:unregister_netdevice: waiting for lo to become free. Usage count = 1
```

A quick google suggests older kernels or old docker demon may be to blame particularly on centos. 

 Whats your distro, kernel and docker version?
