### ISSUE TITLE
 os monitor the loading data  stopped 

### ISSUE THREAD

**Issue by tsh-box** [me-box/databox#264]
Hello,

databox_container-manager.1.kog7wg2xfh8s@tshdatabox    | [Proxy] ERROR: /app-os-monitor/ui getaddrinfo ENOTFOUND app-os-monitor app-os-monitor:8080
databox_container-manager.1.kog7wg2xfh8s@tshdatabox    | [Proxy] retry /app-os-monitor/ui
databox_container-manager.1.kog7wg2xfh8s@tshdatabox    | [databox-request] ExternalRequest https://app-os-monitor:8080/ui
databox_container-manager.1.kog7wg2xfh8s@tshdatabox    | [Proxy] GET: /app-os-monitor/ui/mem.png?rand=0 => https://app-os-monitor:8080/ui/mem.png?rand=0
databox_container-manager.1.kog7wg2xfh8s@tshdatabox    | [databox-request] ExternalRequest https://app-os-monitor:8080/ui/mem.png?rand=0
databox_container-manager.1.kog7wg2xfh8s@tshdatabox    | [Proxy] ERROR: /app-os-monitor/ui/mem.png?rand=0 getaddrinfo ENOTFOUND app-os-monitor app-os-monitor:8080
databox_container-manager.1.kog7wg2xfh8s@tshdatabox    | [Proxy] retry /app-os-monitor/ui/mem.png?rand=0

**Comment by Toshbrown** [comment]
This is a problem with the node proxying, I've been trying to track it down for a while but have been unsuccessful. The container manager is undergoing a full rewrite on golang for a number of reasons. Hopefully, this will resolve this issue and many others.
