### ISSUE TITLE
Arbiter rewrite

### ISSUE THREAD

**Issue by jptmoore** [me-box/databox#265]
I have created a basic zest-based arbiter which is capable of minting databox tokens for testing against the store (zestdb). It is light-weight in RAM compared to the node version (about 3MB compared to 44MB).

It is available here: https://github.com/jptmoore/arbiter

I have not yet implemented the existing arbiter functionality as it would be good at this point to discuss what (if anything) needs changing. I also did not find any documentation on the current API other than looking at the code itself.

**Comment by haddadi** [comment]
This is great space saving! I think would be good to move over from the old arbiter, for easier integration as the platform gets used and we start using the arbiter for apps.

**Comment by Toshbrown** [comment]
Cool, 

Nice savings! API is documented in the readme https://github.com/me-box/core-arbiter

There are some more docs [here](https://github.com/me-box/documents/blob/master/specs/token-auth.md) and [here](https://github.com/me-box/core-arbiter/blob/master/docs/further-info.md). Thay looks reasonably up-to-date at first glance. 
 
Most of the API is seems fit for purpose, but it's worth revisiting the path based tokens as the core-store is no longer a REST API. 

@mor1 we should add this to the platform skype on Tuesday.

**Comment by mor1** [comment]
saw the notes. looks good. @jptmoore eta on supporting rest of api?

**Comment by jptmoore** [comment]
Should take a couple days to translate to zest.

**Comment by Toshbrown** [comment]
This has now been integrated and will be in the next version

**Comment by Toshbrown** [comment]
released in 0.5.0
