### ISSUE TITLE
allow configurable manifest repos

### ISSUE THREAD

**Issue by tlodge** [me-box/databox#278]
Provide a config option to add additional github repos as app stores in the driver-app-store app

**Comment by Toshbrown** [comment]
@tlodge 

I've added this to the latest version of databox you can test it by running 
```
docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd)/certs:/certs -v $(pwd)/sdk:/sdk -v -t databoxsystems/databox:latest /databox start --host-path $(pwd) -sslHostName $(hostname) -release latest
```

The UI is a bit ropey, I'll try and get some time to tidy it up
