### ISSUE TITLE
Is it work the export service in every apps of v0.5.0? 

### ISSUE THREAD

**Issue by tsh-box** [me-box/databox#286]
hello,
I have testing the v0.5.0 Databox,and I installed the app-os-monitor but it does not work export service .
Is it work the export service in every apps of v0.5.0? 

thanks,

**Comment by Toshbrown** [comment]
The export function has been removed from app-os-monitor as its being rewritten and lib-go-databox no longer supports the old version. lib-node-databox and app-twitter-sentiment still support the old version and are working.
