### ISSUE TITLE
databox-install-component ask you for more arguments even when there is no need.

### ISSUE THREAD

**Issue by mmalekzadeh** [me-box/databox#287]
When you want to install a component, it gives you this error:

```
$ ./databox-install-component driver-os-monitor 

Please invoke this script with the component you would like to install.
Usage: databox-install-component [OPTION...] [GITHUB-USER/COMPONENT-NAME] [DATABOX_REPO_TAG] [DATABOX_VERSION]
Flags:
-h     This help message

```

might be this [line](https://github.com/me-box/databox/blob/62440d509ad31bca4eb570bd12926bc2d0b2b160/databox-install-component#L68):

`if [[ $# < 3 ]] || [[ "$1" == "-h" ]]  # Must have more than 1 args.`

**Comment by Toshbrown** [comment]
[DATABOX_REPO_TAG] [DATABOX_VERSION] are required. 

databoxsytems and 0.5.0 respectively if your starting databox as per the readme
