### ISSUE TITLE
it takes too long accessing the databox contents from android app databox

### ISSUE THREAD

**Issue by tsh-box** [me-box/databox#288]
Hi,
I have installed the Databox v0.5.0 in Azure vm.
and then I accessed this URL  in an databox app in android .
My nexus 6 android have memory 2.9G and Android version is 7.1.

And I installed the driver and app for os-monitor  from PC and connected the Databox with android app.
So I want to confirmed the installed driver and app in android app ,When I tapped the menu ,but it takes too long and cannot see any driver.

Could you pointed the procedure where is fault and why does occurs?
Thanks

**Comment by Toshbrown** [comment]
I think the mobile app is in the process of being updated to work with 0.5.0 @ktg should be able to provide more information.

**Comment by tsh-box** [comment]
@ktg please could you support about this?

**Comment by ktg** [comment]
The app is being updated to support 0.5.0. A new version should be ready by the end of next week, at the latest. I will update here when it is ready.

**Comment by tsh-box** [comment]
thanks you
