### ISSUE TITLE
Other than export service,to get the data  from Databox,is there any way?

### ISSUE THREAD

**Issue by tsh-box** [me-box/databox#293]
Hello,
Now export service does not support in some app.
So, Is there any way to get the data of app in external server.

**Comment by Toshbrown** [comment]
The export service is still supported and used. Its the only way to get data from an app to an outside server.

**Comment by tsh-box** [comment]
On v0.5.0,Can export data from app-os-monitor?

**Comment by Toshbrown** [comment]
It was removed from app-os-monitor, I'm releasing 0.5.1 in today so will look at adding it back in.

**Comment by tsh-box** [comment]
I have installed the app-os-monitor,but does not export to https://export.amar.io/

**Comment by Toshbrown** [comment]
0.5.1 is now available and the export service has been added back in. Run:

```
docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v -t databoxsystems/databox:0.5.1 /databox start -sslHostName $(hostname)
``` 

Apologies for the delay
