### ISSUE TITLE
core-ui and core-container-manager fail when built from source

### ISSUE THREAD

**Issue by cgreenhalgh** [me-box/databox#310]
The build step for these containers uses "golang:alpine" which appears to have recently moved from 3.8 to 3.9. The final container is explicitly 3.8. This seems to result in different (incompatible) versions of zmq lib being used in the build and the runtime.

**Comment by Toshbrown** [comment]
Thanks, I'll take a look.

**Comment by Toshbrown** [comment]
I think I have found all of these now. This should be resolved.
