### ISSUE TITLE
Upload local manifest fails using Chrome on Windows due to "incorrect file type"

### ISSUE THREAD

**Issue by cgreenhalgh** [me-box/databox#314]
On my windows machine, in the app store settings under "Upload local manifest", after selecting a .json manifest file and pressing "Add manifest" the driver-app-store refuses to upload it with the error "Incorrect file type". On checking, the browser reports the filetype as "text/plain" and the app-store is checking for "json" in the mime type. This may well work on other platforms, but browser/system mime type guessing is known to be brittle, especially on Windows [see note](https://developer.mozilla.org/en-US/docs/Web/API/File/type#Example)

**Comment by Toshbrown** [comment]
You may need to pull the image manually to get the updated code. 

```
docker pull -t databoxsystems/driver-app-store-amd64:0.5.2
docker pull -t databoxsystems/driver-app-store-arm64v8:0.5.2
```
