### ISSUE TITLE
Permissions not set correctly for exported functions

### ISSUE THREAD

**Issue by cgreenhalgh** [me-box/databox#315]
If I create an app which uses a datasource which is a function (e.g. container manager's ListAllDatasources) then the attempt to call the function fails with unauthorised.

This appears to be because the hypercat information for the function, generated in [Func.Register](https://github.com/me-box/lib-go-databox/blob/master/coreStoreNotifications.go#L66) does not add metadata urn:X-databox:rels:isFunc true as expected by [IsFunc](https://github.com/me-box/lib-go-databox/blob/master/helperFunction.go#L149) and used in the CM to set function-specific permissions (rather than general datasource permissions).

**Comment by Toshbrown** [comment]
Thanks for tracking this down. Should be fixed in v0.6.6 which I have just released.
