### ISSUE TITLE
Pre-generate HTTPS certs

### ISSUE THREAD

**Issue by yousefamar** [me-box/databox#34]
I was thinking about this since it affects SOSP evaluations. Right now app/driver install time is not insignificant, and the majority of a time a container takes to start up is used for generating HTTPS certificates. It would be cool to pre-generate a pool of certs that the CM can just grab and pass on to containers as they start, and top the pool up during idle time. Would make app/driver startup significantly faster.

**Comment by Toshbrown** [comment]
This may change (or at least be affected by) a move to docker swarm as it handles the cert generation differently.

**Comment by Toshbrown** [comment]
[removed] wrong issue ;-)

**Comment by Toshbrown** [comment]
Certs and secrets for the platform components are now pre-generated reducing startup time.
