### ISSUE TITLE
Driver to store streaming API

### ISSUE THREAD

**Issue by Toshbrown** [me-box/databox#38]
When performing a bulk import or dealing with high data rate data sources using the REST API is inefficient. 

We support streaming data for stores --> app  (Reading) but not for Driver --> Store (Writing)

**Comment by yousefamar** [comment]
Perhaps one approach would be for stores to recognise "keep-alive" headers and maintain persistent connections (as opposed to another WS API).

**Comment by cgreenhalgh** [comment]
IMO allowing multiple/bulk add in a single request is more important than making individual requests more efficient. This is a clear win for bulk import, but also allows high data-rate sources to do their own chunking of data.

**Comment by Toshbrown** [comment]
This will be addressed by the new store https://github.com/me-box/databox/issues/104
