### ISSUE TITLE
Running in dev mode on network mounted home dirs

### ISSUE THREAD

**Issue by jptmoore** [me-box/databox#39]
Home directories on the CL machines are network mounted which is causing a problem launching in dev mode when trying to write to ./certs and ./slaStore.

**Comment by Toshbrown** [comment]
The error generated is this: 

Using dev registry:: localhost:5000
/cm/node_modules/nedb/lib/datastore.js:77
    if (err) { throw err; }
               ^

Error: ENOENT: no such file or directory, open './slaStore/sladatastore.db'

Workaround by moving the databox dir to a physical disk.

 It is worth checking if the write to these directories is still needed (could be a hangover from an old version/feature). Worth looking at when we fix # @ #25.

**Comment by jptmoore** [comment]
@mor1 suggested running from a scratch drive which solved the problem.

sudo cl-mkscratchdir (does the trick)
