### ISSUE TITLE
Moving to docker swarm mode

### ISSUE THREAD

**Issue by Toshbrown** [me-box/databox#42]
I've created fet/swarm branches on the main platform components to support moving to docker swarm mode. 

~~The main repo is here https://github.com/Toshbrown/databox-swarm (this will become me-box/databox and me-box/databox will be moved to me-box/databox-cm)~~

This addresses #3 and will make #11, #25 and #34 easier. 

It also makes the startup times shorter, development easier and things more stable generally. 

Please give it a test and comment on this issue. There is a lot of tidying up still to do but this may have an impact on other planned work so I thought it best to share. 

Cheers

Tosh

**Comment by Toshbrown** [comment]
This has been merged into the dev branch via PR #44 

I will leave this issue open as we still need to track updates to other components. 

Until this is merged into the master branch then fet/swarm branches for platform components should be used.

**Comment by haddadi** [comment]
@sevenEng @yousefamar might be good to give a thorough check on arbiter and stores before the big merge?

**Comment by Toshbrown** [comment]
All merged and now released
