### ISSUE TITLE
DATABOX_DEV Issue for ARM

### ISSUE THREAD

**Issue by alibreza** [me-box/databox#43]
I tried to build Databox in DEV mode for arm/raspberry Pi without the DATABOX_DEV flag and using the default store and registry, but I got  the following error : 
`{ Error: Hostname/IP doesn't match certificate's altnames: "Host: databox-arbiter-arm. is not in the cert's altnames: DNS:databox-arbiter, DNS:localhost"
    at Object.checkServerIdentity (tls.js:199:17)
    at TLSSocket.<anonymous> (_tls_wrap.js:1087:29)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:186:7)
    at TLSSocket._finishInit (_tls_wrap.js:599:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:429:38)
  reason: 'Host: databox-arbiter-arm. is not in the cert\'s altnames: DNS:databox-arbiter, DNS:localhost',
  host: 'databox-arbiter-arm',
  cert: 
   { subject: { CN: 'databox-arbiter' },
     issuer: { CN: 'databox' },
     subjectaltname: 'DNS:databox-arbiter, DNS:localhost',
     modulus: ...
Error
    at httpsHelper.init.then.then.then.then.then.then.then.then.then.then.then.then.then.then.then.then.catch.err (/cm/src/main.js:156:17)
    at process._tickCallback (internal/process/next_tick.js:103:7)
npm info lifecycle databox-container-manager@0.1.0~poststart: databox-container-manager@0.1.0
npm info ok 
/usr/bin/entry.sh: line 93: fg: job has terminated`

In order to resolve the issue, I changed  the following line in [container-manager.js](https://github.com/me-box/databox/blame/34a128c556d857e0edfc4cf2861a229034bafc1d/src/container-manager.js#L445) :

`launchPlatformContainer("databox-arbiter",config,networks,5000)`
changed to
`launchPlatformContainer("databox-arbiter"**+ ARCH**,config,networks,5000)`
Now, Databox is launched without any errors and I can install the drivers and apps, but they won't be running because of missing parameters:
`npm info it worked if it ends with ok
npm info using npm@4.1.2
npm info using node@v7.6.0
npm info lifecycle databox-driver-mobile@0.1.0~prestart: databox-driver-mobile@0.1.0
npm info lifecycle databox-driver-mobile@0.1.0~start: databox-driver-mobile@0.1.0

> databox-driver-mobile@0.1.0 start /
> node main.js

Missing parameters
[waitForStoreStatus] Retrying in 1s...
Missing parameters
npm info lifecycle databox-driver-mobile@0.1.0~poststart: databox-driver-mobile@0.1.0
npm info ok 
/usr/bin/entry.sh: line 93: fg: job has terminated`

**Comment by Toshbrown** [comment]
Hi, 

Thanks for trying out databox. ARM support is very experimental at the moment, only a limited set of features work. As far as I know DEV mode on ARM has never been tested and will be missing some required docker images. It should run in normal mode though. 

If you want to test/develop right now, then the development branch is stable on x86 and has been tested in Linux and docker for macOS. 

Fixing ARM is on the TODO list but I can't give you a timescale for getting it working. What were you hoping to achieve, what's your time scale?

**Comment by alibreza** [comment]
For the beginning, I've been trying to configure databox to use another external store and registry for the container images instead of the official ones.

Since I just disabled the DATABOX_DEV flag and it's using the official registry and store, I supposed it should work similar to the normal mode. 

Although currently I need to work on ARM for my research project, I've tried the stable branch on x86, but it seems the databox-export-service isn't working as well. I considered this line as one of possible [typo](https://github.com/me-box/databox/blob/34a128c556d857e0edfc4cf2861a229034bafc1d/src/container-manager.js#L517) causes for the problem.

Now I just need a working source code of official **databox-cm-arm** docker image which allows me to do some modifications.

**Comment by Toshbrown** [comment]
Hi, 

I'm currently undertaking a big refactor of the databox-cm and startup process. The new code should be in the dev branch today. The benefit of the new structure is that we no longer need a local registry for development and all images for the platform are built locally. This should make developing on ARM much easier.

Once I've got the code in better shape and integrated I will take a look at getting it running on ARM.

**Comment by Toshbrown** [comment]
aarch64 support is now in the dev branch I will get arm7l working for the Pi next

**Comment by Toshbrown** [comment]
armv7l support is now in the development branch and has been tested as working on a Rpi3.

The way the code is structured and started has been changed but the APIs are all still the same. 

I will leave this open for a while, comment here if you are having problems.

Cheers 

Tosh

**Comment by Toshbrown** [comment]
ARM device should now work. I will close this now. Feel free to open new issues if you are still having trouble.
