### ISSUE TITLE
make node-datastore library and datasource environment variables consistent

### ISSUE THREAD

**Issue by cgreenhalgh** [me-box/databox#5]
Currently the node-datastore library has separate arguments for the datastore URL and the datasource ID which are internally munged to the datasource URL, but the CM passes the combined URL to apps/drivers in the Datasource environment variable(s).

Either the node-datastore library should accept the combined URL or the environment variable should include the separate values. (Note that if the library is changed then subscription connect operation may need to actively discard the datasource id path component.)

**Comment by yousefamar** [comment]
I think the former (combined URL acceptance by lib) is better. I've been meaning to get to this for a while now; please assign me to this issue so I don't lose it. (Org admins, please add "databox" as collaborator on me-box/databox like the other repos, so I can do that myself from now on?). Should close https://github.com/me-box/node-databox/issues/12 when resolved too.

**Comment by mor1** [comment]
@yousefamar Done (I think).

**Comment by haddadi** [comment]
have fixed the team permissions now

also agree that the former is better.. maybe we should spec up a unified method for this across modules
