### ISSUE TITLE
Docker swarm on machines with multiple IP addresses

### ISSUE THREAD

**Issue by dominicjprice** [me-box/databox#51]
On machines with more than one IP address, docker swarm cannot determine with IP to use and needs the --advertise-addr option.

**Comment by Toshbrown** [comment]
I think this should solve the problem:

ifconfig | sed -En 's/127.0.0.1//;s/169.*//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p'

Can you give it try and see if it returns the right address on your machine? 

If it works I will add it in the startup scripts.

Seems to work well on MacOS

Cheers

Tosh

**Comment by tsh-box** [comment]
i also solved by adding the following options
docker swarm init --advertise-addr 192.168.44.99 --listen-addr 0.0.0.0

**Comment by Toshbrown** [comment]
can any one confirm that running 

ifconfig | sed -En 's/127.0.0.1//;s/169.//;s/.inet (addr:)?(([0-9].){3}[0-9]).*/\2/p'

returns the external IP? I don't have a machine to test it on. 

Cheers 

Tosh

**Comment by dominicjprice** [comment]
On Ubuntu 16.04.2 it returns:
"         192.168"
where I have multiple IP addresses.

**Comment by tsh-box** [comment]
On centOs7,it returns :
"192.168"

**Comment by dominicjprice** [comment]
@Toshbrown This should work
`ifconfig | sed -En 's/127.0.0.1//;s/169.//;s/.inet (addr:)?(([0-9]+.){3}[0-9]+).*/\2/p'`
Though you may need to filter out any virtual interfaces (e.g. Docker, Virtualbox). Also, on machines like mine where I am connected via ethernet and wifi, I have two 'public' IP addresses (I know, I'm a pain).
