### ISSUE TITLE
Apps installing error 

### ISSUE THREAD

**Issue by tsh-box** [me-box/databox#63]
I built Databox with 'sh startDatabox.sh dev'
and UI is successfully done and I also installed app-light-graph from Apps menu 
and then following error occurs .

databox_container-manager.1.5fhagepah3ur@databox    | [Proxy] ERROR: /app-light-graph/ui getaddrinfo ENOTFOUND app-light-graph app-light-graph:8080
databox_container-manager.1.5fhagepah3ur@databox    | [Proxy] POST: /store/app/get/ => http://app-server:8181/app/get/
databox_container-manager.1.5fhagepah3ur@databox    | [databox-request] ExternalRequest http://app-server:8181/app/get/
databox_container-manager.1.5fhagepah3ur@databox    | [Proxy] GET: /arbiter/cat => https://arbiter:8080/cat
databox_container-manager.1.5fhagepah3ur@databox    | [Proxy] GET: /app-light-graph-databox-store-blob/cat => https://app-light-graph-databox-store-blob:8080/cat
databox_container-manager.1.5fhagepah3ur@databox    | [macaroonCache] cashed macaroon not found for app-light-graph-databox-store-blob/catGET requesting one
databox_container-manager.1.5fhagepah3ur@databox    | [macaroonCache] API Error::  Target app-light-graph-databox-store-blob has not registered itself for arbitering
databox_container-manager.1.5fhagepah3ur@databox    | undefined
databox_container-manager.1.5fhagepah3ur@databox    | (node:15) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): undefined
databox_container-manager.1.5fhagepah3ur@databox    | (node:15) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Toshbrown** [comment]
This looks like a manifest error:

app-light-graph-databox-store-blob has not registered itself for arbitering

databox-store-blob has been renamed to store-json

I'm taking a look at this now.

**Comment by Toshbrown** [comment]
tested and working:

Install driver-sensingkit and enable the light sensor first 

then play with the Time Window and Entry Window sliders.

**Comment by tsh-box** [comment]
Thanks!
app-light-graph installation does not occurs error ,and I also installed 
driver-sensingkit that is also OK.By the way,
How  are you doing "enable the light sensor first then play with the Time Window and Entry Window sliders."?



--
