### ISSUE TITLE
/run/secrets/DATABOX_PEM is not pem format

### ISSUE THREAD

**Issue by Toshbrown** [me-box/databox#64]
DATABOX_PEM is a json representation of a PEM file should just be a standard PEM file

Changes will be put into a PEM branch on each component then all merged together at the same time. 

This will require changes to:

- [x]  core-container-manager 
- [x]  core-syslog 
- [x]  core-arbiter 
- [x]  core-export-service 

### Store
- [x]  store-json
- [x]  store-timeseries 

### Lib
- [x]  lib-python-databox
- [x] lib-node-databox 

### Driver 
- [x] driver-sensingkit
- [x] driver-google-takeout
- [x] driver-phillips-hue
- [x] driver-twitter
- [x] driver-os-monitor

### App
- [x]  app-light-graph
- [x]  app-twitter-sentiment

**Comment by yousefamar** [comment]
Apropos, having a `targetPlatformVersion` or similar (#6) in manifest specs would be perfect for changes like this before the number of drivers/apps start to grow, so I'm thinking priority++ for #6.

**Comment by Toshbrown** [comment]
Just for reference to make this migration easier I have added getHttpsCredentials to lib-node-databox to remove repeated databox API specific code in apps.

**Comment by Toshbrown** [comment]
I will close this now everything has been updated.
