### ISSUE TITLE
docker swarm init error 

### ISSUE THREAD

**Issue by tsh-box** [me-box/databox#65]
When I executed " sh startDatabox.sh",the following process and error occurs
Error response from daemon: This node is not a swarm manager. Use "docker swarm init" or "docker swarm join" to connect this node to swarm and try again.
More than one IP found please select from the list.
1) 172.17.0.1
2) 10.0.2.15
3) 192.168.44.91
#? 192.168.44.91
flag needs an argument: --advertise-addr
See 'docker swarm init --help'.
Ignoring unsupported options: build

this node is not a swarm manager. Use "docker swarm init" or "docker swarm join" to connect this node to swarm and try again
[seeding manifest] waiting for appstore
[seeding manifest] waiting for appstore
[seeding manifest] waiting for appstore

**Comment by Toshbrown** [comment]
Hi, 

Can you provide some more information?

What branch, OS, docker version? 

Also, how did you select the IP address?  Did you type the full address?

**Comment by tsh-box** [comment]
hello!
I cloned the latest source code form me/databox repos and I built the virtual machine OS(centos7) using vagrant and then installed requirements(docker,pip,docker-compose,etc;) that are also latest version  and then I executed 'sh startDatabox.sh' comment.
In Command promant,asking IP like as following 
More than one IP found please select from the list.
1) 172.17.0.1
2) 10.0.2.15
3) 192.168.44.91
#? 
And then I type 192.168.44.91 and press enter
And Finally error occurs , 
flag needs an argument: --advertise-addr
See 'docker swarm init --help'.
Creating certs
./certs/arbiter.json arbiter
./certs/export-service.json export-service
./certs/syslog.json syslog
Done!
Ignoring unsupported options: build

this node is not a swarm manager. Use "docker swarm init" or "docker swarm join" to connect this node to swarm and try again
[seeding manifest] waiting for appstore
[seeding manifest] waiting for appstore

**Comment by Toshbrown** [comment]
"then I type 192.168.44.91 and press enter"

Just use 1,2 or 3 to select the IP do not type the address.

**Comment by tsh-box** [comment]
oh! 
why i don't think about it , Thanks you. 
error is clear :)

**Comment by Toshbrown** [comment]
Glad it's fixed. 

Cheers 

Tosh

**Comment by tsh-box** [comment]
Cheers! :)
Could I inquire about Databox?
Is it work the export service in Databox?
Is Databox possible to connect with external server[example; PPM server]?
Thanks,
