### ISSUE TITLE
driver does not work?

### ISSUE THREAD

**Issue by tsh-box** [me-box/databox#66]
hello! 
I installed a driver(driver-google-takeout) .
When I click the running driver ,the following error is shown and attached the UI screenshot

databox_container-manager.1.mbeeoexq23sk@databox    | [Proxy] GET: /driver-google-takeout/ui => https://driver-google-takeout:8080/ui
databox_container-manager.1.mbeeoexq23sk@databox    | [databox-request] ExternalRequest https://driver-google-takeout:8080/ui
databox_container-manager.1.mbeeoexq23sk@databox    | [Proxy] ERROR: /driver-google-takeout/ui connect ECONNREFUSED 10.0.4.11:8080
databox_container-manager.1.mbeeoexq23sk@databox    | [Proxy] GET: /driver-google-takeout/ui => https://driver-google-takeout:8080/ui
databox_container-manager.1.mbeeoexq23sk@databox    | [databox-request] ExternalRequest https://driver-google-takeout:8080/ui
databox_container-manager.1.mbeeoexq23sk@databox    | [Proxy] ERROR: /driver-google-takeout/ui getaddrinfo ENOTFOUND driver-google-takeout driver-google-takeout:8080
![000](https://user-images.githubusercontent.com/29420329/28451706-ced4aac2-6e29-11e7-8b1a-5fa40f2ad17a.png)

**Comment by Toshbrown** [comment]
can you post the output of the following 

docker info; docker ps; docker service ls; docker stack ps databox; docker service logs driver-google-takeout; docker image ls | grep driver

**Comment by tsh-box** [comment]
[vagrant@databox databox-master]$ docker info
Containers: 20
 Running: 5
 Paused: 0
 Stopped: 15
Images: 9
Server Version: 17.06.0-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: 57853cp11i6fftuqc4ulxjp5r
 Is Manager: true
 ClusterID: o38azcjfui1l1ctxlv4ekz87x
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Root Rotation In Progress: false
 Node Address: 192.168.44.91
 Manager Addresses:
  192.168.44.91:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.26.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 488.7MiB
Name: databox
ID: ZC3S:WBTR:BADY:2K74:XB3S:YHNV:GAIC:XTKA:JEEL:OWCF:DYKM:WDLD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
//////////////////////////////////////////////////////////////////////////

[vagrant@databox databox-master]$ docker ps
CONTAINER ID        IMAGE                                     COMMAND             CREATED             STATUS              PORTS                NAMES
9487d9e00099        databoxsystems/app-light-graph:latest     "npm start"         5 seconds ago       Up 1 second         8080/tcp             app-light-graph.1.wzzh9ia2brstks7gwwcvfz0cf
e0fb9e7e0a77        databoxsystems/syslog:latest              "npm start"         6 hours ago         Up 6 hours          8080/tcp             databox_syslog.1.fo2emr52b8byntel94adftlhd
2fd3f3ff7911        databoxsystems/arbiter:latest             "npm start"         6 hours ago         Up 6 hours          8080/tcp             databox_arbiter.1.wkjswbaemwnodbl8y6uctt7o6
168886e3c0c2        databoxsystems/container-manager:latest   "npm start"         6 hours ago         Up 6 hours          8989/tcp             databox_container-manager.1.k1gabtbnwicvdmajdy1w847fz
6e7b0849b678        databoxsystems/app-server:latest          "npm start"         6 hours ago         Up 6 hours          8080/tcp, 8181/tcp   databox_app-server.1.vfioflo4b8lkdfpu27qeu7v4r
[vagrant@databox databox-master]$
//////////////////////////////////////////////////////////////

[vagrant@databox databox-master]$ docker service ls
ID                  NAME                            MODE                REPLICAS            IMAGE                                     PORTS
22diss8tv52v        databox_arbiter                 replicated          1/1                 databoxsystems/arbiter:latest
8mims0oca7l3        driver-sensingkit-store-json    replicated          0/1                 store-json
hfnqx3j7dayg        databox_syslog                  replicated          1/1                 databoxsystems/syslog:latest
kqg96c91k8cs        app-light-graph                 replicated          0/1                 databoxsystems/app-light-graph
l3ixu1gf61je        databox_export-service          replicated          0/1                 databoxsystems/export-service:latest
lqtj6kumhcrr        databox_container-manager       replicated          1/1                 databoxsystems/container-manager:latest   *:8989->8989/tcp
o8nz2a645doz        driver-hello-world              replicated          0/1                 databoxsystems/driver-hello-world
r906zahd2li8        databox_app-server              replicated          1/1                 databoxsystems/app-server:latest          *:8181->8181/tcp
tk281x4ttymd        driver-hello-world-store-json   replicated          0/1                 store-json
w4hrul9svhb4        app-light-graph-store-json      replicated          0/1                 store-json
wrmdnnjr9e8w        driver-sensingkit               replicated          1/1                 databoxsystems/driver-sensingkit
//////////////////////////////////////////////////////////////////////////////////////

[vagrant@databox databox-master]$ docker stack ps databox
ID                  NAME                           IMAGE                                     NODE                DESIRED STATE       CURRENT STATE           ERROR                       PORTS
kqxyb9wl40t7        databox_export-service.1       databoxsystems/export-service:latest      databox             Running             Starting 1 second ago
nyj0dls7i97q         \_ databox_export-service.1   databoxsystems/export-service:latest      databox             Shutdown            Failed 7 seconds ago    "task: non-zero exit (1)"
yrqnh70r4c4r         \_ databox_export-service.1   databoxsystems/export-service:latest      databox             Shutdown            Failed 15 seconds ago   "task: non-zero exit (1)"
hpvkjgy76xzs         \_ databox_export-service.1   databoxsystems/export-service:latest      databox             Shutdown            Failed 21 seconds ago   "task: non-zero exit (1)"
tqdztgq980kx         \_ databox_export-service.1   databoxsystems/export-service:latest      databox             Shutdown            Failed 27 seconds ago   "task: non-zero exit (1)"
fo2emr52b8by        databox_syslog.1               databoxsystems/syslog:latest              databox             Running             Running 6 hours ago
wkjswbaemwno        databox_arbiter.1              databoxsystems/arbiter:latest             databox             Running             Running 6 hours ago
k1gabtbnwicv        databox_container-manager.1    databoxsystems/container-manager:latest   databox             Running             Running 6 hours ago
vfioflo4b8lk        databox_app-server.1           databoxsystems/app-server:latest          databox             Running             Running 6 hours ago
[vagrant@databox databox-master]$
///////////////////////////////////////////////////////////

[vagrant@databox databox-master]$ docker service logs driver-google-takeout
no such task or service: driver-google-takeout
///////////////////////////////////////////////////////////

[vagrant@databox databox-master]$ docker image ls | grep driver
databoxsystems/driver-google-takeout   latest              55d8d7d9b1e5        6 days ago          81.8MB
databoxsystems/driver-sensingkit       latest              d9228ad8f70e        6 days ago          80.5MB

Thanks you,

**Comment by Toshbrown** [comment]
Ok, I think I have spotted and fixed the issue. 

> tk281x4ttymd driver-hello-world-store-json replicated 0/1 store-json
w4hrul9svhb4 app-light-graph-store-json replicated 0/1 store-json

It's using your local store when you're not running in dev mode. 

can you give it a go on the master branch in normal mode first? 

Cheers

Tosh

**Comment by tsh-box** [comment]
I used the latest code from master branch and executed 'sh startDatabox.sh',but it takes too time for starting UI about 1:30 hours ,previous day does not takes too time 
![000](https://user-images.githubusercontent.com/29420329/28510009-c696ccce-7080-11e7-8e70-2249d3c42ea5.png)

And then I deleted it and rebuild databox ,The following error occurs

![1111](https://user-images.githubusercontent.com/29420329/28510538-f5ba80ce-7083-11e7-9ee1-6d96f1199dd9.png)

**Comment by Toshbrown** [comment]
When you run ./startDatabox.sh the images are pulled from https://hub.docker.com/u/databoxsystems/

If you are on a slow network connection or there is an issue with hub.docker.com startup times can be slow. 

can you post the output of:

docker image ls | grep 'driver\|app\|store'

docker service ls

**Comment by laelaeaung** [comment]
![1111](https://user-images.githubusercontent.com/29420329/28513204-1c09e40c-7090-11e7-9974-1affb2ce770e.png)

UI does not complete yet.

**Comment by tsh-box** [comment]
[vagrant@databox ~]$ docker service ls
ID                  NAME                           MODE                REPLICAS            IMAGE                                     PORTS
1j2co7k0geol        databox_syslog                 replicated          1/1                 databoxsystems/syslog:latest
gvmx25ihewyz        databox_container-manager      replicated          1/1                 databoxsystems/container-manager:latest   *:8989->8989/tcp
h7yd3zs9s6r3        driver-sensingkit-store-json   replicated          0/1                 databoxsystems/store-json
l02qpcksopru        databox_arbiter                replicated          1/1                 databoxsystems/arbiter:latest
spbu7wyiy76b        databox_app-server             replicated          1/1                 databoxsystems/app-server:latest          *:8181->8181/tcp
yjrjzxsk1fe2        databox_export-service         replicated          1/1                 databoxsystems/export-service:latest
zob9x1v5hu1l        driver-sensingkit              replicated          0/1                 databoxsystems/driver-sensingkit
[vagrant@databox ~]$ docker image ls | grep 'driver|app|store'
[vagrant@databox ~]$
//////////////////////////////////////////
When I installed the driver-sensingkit ,Console error are following,
databox_container-manager.1.n2xmvxn7gdz0@databox    | [Adding write permissions] for driver-sensingkit-store-json on syslog/driver-sensingkit-store-json
databox_container-manager.1.n2xmvxn7gdz0@databox    | [driver-sensingkit] Installed [ 'driver-sensingkit', 'driver-sensingkit-store-json' ]
databox_container-manager.1.n2xmvxn7gdz0@databox    | Proxy added for  driver-sensingkit
databox_container-manager.1.n2xmvxn7gdz0@databox    | Proxy added for  driver-sensingkit-store-json
databox_container-manager.1.n2xmvxn7gdz0@databox    | [Proxy] GET: /driver-sensingkit/ui => https://driver-sensingkit:8080/ui
databox_container-manager.1.n2xmvxn7gdz0@databox    | [databox-request] ExternalRequest https://driver-sensingkit:8080/ui
databox_container-manager.1.n2xmvxn7gdz0@databox    | [Proxy] ERROR: /driver-sensingkit/ui getaddrinfo EAI_AGAIN driver-sensingkit:8080

**Comment by Toshbrown** [comment]
docker image ls | grep 'driver\\|app\\|store'

should return a list of images? 

try it without the grep "docker image ls"

If you can't see any images has your vagrent vm got external network access?

**Comment by tsh-box** [comment]
[vagrant@databox ~]$ docker image ls | grep 'driver\|app\|store'
databoxsystems/driver-sensingkit   latest              ffa29b4276a2        2 days ago          82.2MB
databoxsystems/store-json          latest              b582b0a9e53a        2 days ago          167MB
databoxsystems/app-server          <none>              1df9da67fb81        9 days ago          91.3MB
[vagrant@databox ~]$ docker image ls
REPOSITORY                         TAG                 IMAGE ID            CREATED             SIZE
node                               alpine              442930c9c9fb        2 days ago          64.6MB
databoxsystems/export-service      <none>              0096cb2c9cd5        2 days ago          22.8MB
databoxsystems/container-manager   <none>              c23e55380c6e        2 days ago          193MB
databoxsystems/driver-sensingkit   latest              ffa29b4276a2        2 days ago          82.2MB
databoxsystems/arbiter             <none>              26769a7daf0e        2 days ago          96.5MB
databoxsystems/syslog              <none>              44bdc91e05da        2 days ago          90.3MB
databoxsystems/store-json          latest              b582b0a9e53a        2 days ago          167MB
databoxsystems/app-server          <none>              1df9da67fb81        9 days ago          91.3MB
[vagrant@databox ~]$

**Comment by Toshbrown** [comment]
Few, that looks better. 

I've been testing on docker for mac, just building a VM to test it in Linux to see if I can recreate the issue.

**Comment by tsh-box** [comment]
![image](https://user-images.githubusercontent.com/29420329/28516302-b5cd5e38-709b-11e7-84f1-b480ad390ab0.png)

same display screen when click the driver-sensingkit.
Is need Sources data(mobile data,light etc;) for running Databox UI?

**Comment by Toshbrown** [comment]
Without a source installed then the app just crashes on my databox.

**Comment by tsh-box** [comment]
![000](https://user-images.githubusercontent.com/29420329/28517208-acda7c18-709e-11e7-9e31-8416143fa006.png)

I don't know.What parts now I am testing  according to this Figure :(

**Comment by Toshbrown** [comment]
Tested and working on an Ubuntu 16.04 in VirtualBox.

![screen shot 2017-07-24 at 10 39 37](https://user-images.githubusercontent.com/1186363/28517512-86a84a12-705c-11e7-9ad5-2cd9947937a9.png)

**Comment by Toshbrown** [comment]
you are testing all of it! 

can you join databoxsystems.slack.com so we can take this off gitHub issues?

**Comment by tsh-box** [comment]
yes, I can join Thanks  for your patience.

**Comment by tsh-box** [comment]
I have no account for Slack,how to join databoxsystems.slack.com?

**Comment by Toshbrown** [comment]
skype? toshbrown

**Comment by tsh-box** [comment]
I thought my development environment is strange,so I will install centos7 with GUI on the virtualbox and then databox will build on this environment.If any problem, I will ask you again.

Thank you Tosh :)

**Comment by tsh-box** [comment]
hello!Tosh,
I got it :)
![000](https://user-images.githubusercontent.com/29420329/28553849-011450e6-7131-11e7-972a-6a1cf96aa47d.png)

now i will continue test :)

**Comment by Toshbrown** [comment]
Good stuff, What did you change?

**Comment by tsh-box** [comment]
In last day I used vagrant to install centos7,but now I directly installed centosOS7 with GUI on the virtualBox and cloned the latest code on it and then executed ./startdatabox.sh

**Comment by tsh-box** [comment]
hi,Tosh,
I have installed driver and I want to test it so I need data that get from databox-source-mobile-debug.apk by installing in andriod phone , is it true?

**Comment by Toshbrown** [comment]
yes, you need the android app to test that driver.

I will close this now as you seem to be up and running.
