### ISSUE TITLE
Apps does not received data

### ISSUE THREAD

**Issue by tsh-box** [me-box/databox#67]
I installed a app-light-graph . When I click the running app,the following error is shown and attached the UI screenshot
![000](https://user-images.githubusercontent.com/29420329/28455800-406306dc-6e3b-11e7-9a42-e4b16d24978c.png)

**Comment by Toshbrown** [comment]
can you post any js errors is the browsers developer console and the output of:

docker service logs app-light-graph

**Comment by tsh-box** [comment]
console error are as following 

databox_container-manager.1.k1gabtbnwicv@databox    | [Proxy] GET: /app-light-graph/ui => https://app-light-graph:8080/ui
databox_container-manager.1.k1gabtbnwicv@databox    | [databox-request] ExternalRequest https://app-light-graph:8080/ui
databox_container-manager.1.k1gabtbnwicv@databox    | [Proxy] ERROR: /app-light-graph/ui getaddrinfo EAI_AGAIN app-light-graph:8080
databox_container-manager.1.k1gabtbnwicv@databox    | [Proxy] GET: /app-light-graph/ui => https://app-light-graph:8080/ui
databox_container-manager.1.k1gabtbnwicv@databox    | [databox-request] ExternalRequest https://app-light-graph:8080/ui
databox_container-manager.1.k1gabtbnwicv@databox    | [Proxy] ERROR: /app-light-graph/ui connect ECONNREFUSED 10.0.0.12:8080
databox_container-manager.1.k1gabtbnwicv@databox    | [Proxy] GET: /app-light-graph/ui => https://app-light-graph:8080/ui
databox_container-manager.1.k1gabtbnwicv@databox    | [databox-request] ExternalRequest https://app-light-graph:8080/ui
databox_container-manager.1.k1gabtbnwicv@databox    | [Proxy] ERROR: /app-light-graph/ui connect ECONNREFUSED 10.0.0.12:8080
databox_container-manager.1.k1gabtbnwicv@databox    | [Proxy] GET: /app-light-graph/ui => https://app-light-graph:8080/ui
databox_container-manager.1.k1gabtbnwicv@databox    | [databox-request] ExternalRequest https://app-light-graph:8080/ui
databox_container-manager.1.k1gabtbnwicv@databox    | [Proxy] ERROR: /app-light-graph/ui connect ECONNREFUSED 10.0.0.12:808
/////////////////////////////////////////////////////
I executed 'docker service logs app-light-graph' and logs are following 

app-light-graph.1.7liqplhugt9v@databox    | npm info lifecycle app-light-graph@0.1.0~start: Failed to exec start script
app-light-graph.1.oj4v8glhlyjz@databox    | npm info lifecycle app-light-graph@0.1.0~start: Failed to exec start script
app-light-graph.1.kjomg9nux6a3@databox    | npm info lifecycle app-light-graph@0.1.0~start: Failed to exec start script
app-light-graph.1.luchdb66iudn@databox    | npm info lifecycle app-light-graph@0.1.0~start: Failed to exec start script
app-light-graph.1.luchdb66iudn@databox    | npm ERR! code ELIFECYCLE
app-light-graph.1.7liqplhugt9v@databox    | npm ERR! code ELIFECYCLE
app-light-graph.1.oj4v8glhlyjz@databox    | npm ERR! code ELIFECYCLE
app-light-graph.1.kjomg9nux6a3@databox    | npm ERR! code ELIFECYCLE
app-light-graph.1.kjomg9nux6a3@databox    | npm ERR! errno 1
app-light-graph.1.luchdb66iudn@databox    | npm ERR! errno 1
app-light-graph.1.7liqplhugt9v@databox    | npm ERR! errno 1
app-light-graph.1.oj4v8glhlyjz@databox    | npm ERR! errno 1
app-light-graph.1.oj4v8glhlyjz@databox    | npm ERR! app-light-graph@0.1.0 start: `node server.js`
app-light-graph.1.kjomg9nux6a3@databox    | npm ERR! app-light-graph@0.1.0 start: `node server.js`
app-light-graph.1.luchdb66iudn@databox    | npm ERR! app-light-graph@0.1.0 start: `node server.js`
app-light-graph.1.7liqplhugt9v@databox    | npm ERR! app-light-graph@0.1.0 start: `node server.js`
app-light-graph.1.7liqplhugt9v@databox    | npm ERR! Exit status 1
app-light-graph.1.oj4v8glhlyjz@databox    | npm ERR! Exit status 1
app-light-graph.1.kjomg9nux6a3@databox    | npm ERR! Exit status 1
app-light-graph.1.luchdb66iudn@databox    | npm ERR! Exit status 1
app-light-graph.1.luchdb66iudn@databox    | npm ERR!
app-light-graph.1.7liqplhugt9v@databox    | npm ERR!
app-light-graph.1.oj4v8glhlyjz@databox    | npm ERR!
app-light-graph.1.kjomg9nux6a3@databox    | npm ERR!

**Comment by Toshbrown** [comment]
Right, I've just fixed the other issue and tested this one with the new code and can't replicate the error. 

Can you give it another go and see if it works now? Use the master branch. 

If it's still not working the errors from your web browsers console will be useful. 

Cheers

Tosh

**Comment by tsh-box** [comment]
hi,
I installed app-light-graph,the status of the installation is always suddenly changed such as running,created and exited.so I confirm with docker service ls 

[root@localhost databox]# docker service ls
ID                  NAME                           MODE                REPLICAS            IMAGE                                     PORTS
39kdfam0kjor        databox_app-server             replicated          1/1                 databoxsystems/app-server:latest          *:8181->8181/tcp
60nhrtlsdypd        app-light-graph-store-json     replicated          1/1                 databoxsystems/store-json                 
a9zl57afvouz        databox_container-manager      replicated          1/1                 databoxsystems/container-manager:latest   *:8989->8989/tcp
jefeljvlshsz        databox_export-service         replicated          1/1                 databoxsystems/export-service:latest      
jl3dgdgpkpxh        databox_syslog                 replicated          1/1                 databoxsystems/syslog:latest              
wgu80a6zcygj        databox_arbiter                replicated          1/1                 databoxsystems/arbiter:latest             
wvx45n0totpj        driver-sensingkit-store-json   replicated          1/1                 databoxsystems/store-json                 
y8fqlhgbr938        driver-sensingkit              replicated          1/1                 databoxsystems/driver-sensingkit          
**_yl8dd75eddf1        app-light-graph                replicated          1/1                 databoxsystems/app-light-graph_**            
[root@localhost databox]# docker service ls
ID                  NAME                           MODE                REPLICAS            IMAGE                                     PORTS
39kdfam0kjor        databox_app-server             replicated          1/1                 databoxsystems/app-server:latest          *:8181->8181/tcp
60nhrtlsdypd        app-light-graph-store-json     replicated          1/1                 databoxsystems/store-json                 
a9zl57afvouz        databox_container-manager      replicated          1/1                 databoxsystems/container-manager:latest   *:8989->8989/tcp
jefeljvlshsz        databox_export-service         replicated          1/1                 databoxsystems/export-service:latest      
jl3dgdgpkpxh        databox_syslog                 replicated          1/1                 databoxsystems/syslog:latest              
wgu80a6zcygj        databox_arbiter                replicated          1/1                 databoxsystems/arbiter:latest             
wvx45n0totpj        driver-sensingkit-store-json   replicated          1/1                 databoxsystems/store-json                 
y8fqlhgbr938        driver-sensingkit              replicated          1/1                 databoxsystems/driver-sensingkit          
_**yl8dd75eddf1        app-light-graph                replicated          0/1                 databoxsystems/app-light-graph**_ 

The console log are as following  when I clicked the app-light-graph app,

databox_container-manager.1.kzudxm31uejy@localhost.databox    | [Proxy] GET: /app-light-graph/ui => https://app-light-graph:8080/ui
databox_container-manager.1.kzudxm31uejy@localhost.databox    | [databox-request] ExternalRequest https://app-light-graph:8080/ui
databox_container-manager.1.kzudxm31uejy@localhost.databox    | [Proxy] ERROR: /app-light-graph/ui connect ECONNREFUSED 10.0.1.14:8080
databox_container-manager.1.kzudxm31uejy@localhost.databox    | [Proxy] GET: /app-light-graph/ui => https://app-light-graph:8080/ui
databox_container-manager.1.kzudxm31uejy@localhost.databox    | [databox-request] ExternalRequest https://app-light-graph:8080/ui
databox_container-manager.1.kzudxm31uejy@localhost.databox    | [Proxy] ERROR: /app-light-graph/ui getaddrinfo ENOTFOUND app-light-graph app-light-graph:8080

![1111](https://user-images.githubusercontent.com/29420329/28556232-d184dddc-713f-11e7-90e5-501429359763.png)



and I also confirm the Store Tab,app-light-graph store json is running 

![000](https://user-images.githubusercontent.com/29420329/28556340-ae8ab904-7140-11e7-962d-3e1277cdbc5f.png)

![1111](https://user-images.githubusercontent.com/29420329/28556369-ee8fe51a-7140-11e7-9296-14cf3d98664a.png)

Thank you,

**Comment by Toshbrown** [comment]
Whats the output of:

docker service logs app-light-graph

**Comment by tsh-box** [comment]
[root@localhost databox]# **_docker service logs app-light-graph_**
app-light-graph.1.lg0fhwtmd3el@localhost.databox    | npm info it worked if it ends with ok
app-light-graph.1.d7gjw6ez14tr@localhost.databox    | npm info it worked if it ends with ok
app-light-graph.1.xobwwbnyass5@localhost.databox    | npm info it worked if it ends with ok
app-light-graph.1.u4nc7lxylipd@localhost.databox    | npm info it worked if it ends with ok
app-light-graph.1.u4nc7lxylipd@localhost.databox    | npm info using npm@5.3.0
app-light-graph.1.lg0fhwtmd3el@localhost.databox    | npm info using npm@5.3.0
app-light-graph.1.d7gjw6ez14tr@localhost.databox    | npm info using npm@5.3.0
app-light-graph.1.xobwwbnyass5@localhost.databox    | npm info using npm@5.3.0
app-light-graph.1.xobwwbnyass5@localhost.databox    | npm info using node@v8.2.0
app-light-graph.1.u4nc7lxylipd@localhost.databox    | npm info using node@v8.2.0
app-light-graph.1.lg0fhwtmd3el@localhost.databox    | npm info using node@v8.2.0
app-light-graph.1.d7gjw6ez14tr@localhost.databox    | npm info using node@v8.2.0
app-light-graph.1.d7gjw6ez14tr@localhost.databox    | 
app-light-graph.1.xobwwbnyass5@localhost.databox    | npm info lifecycle app-light-graph@0.1.0~prestart: app-light-graph@0.1.0
app-light-graph.1.u4nc7lxylipd@localhost.databox    | npm info lifecycle app-light-graph@0.1.0~prestart: app-light-graph@0.1.0
app-light-graph.1.lg0fhwtmd3el@localhost.databox    | 
app-light-graph.1.lg0fhwtmd3el@localhost.databox    | > app-light-graph@0.1.0 start /
app-light-graph.1.d7gjw6ez14tr@localhost.databox    | > app-light-graph@0.1.0 start /
app-light-graph.1.xobwwbnyass5@localhost.databox    | npm info lifecycle app-light-graph@0.1.0~start: app-light-graph@0.1.0
app-light-graph.1.u4nc7lxylipd@localhost.databox    | npm info lifecycle app-light-graph@0.1.0~start: app-light-graph@0.1.0
app-light-graph.1.u4nc7lxylipd@localhost.databox    | 
app-light-graph.1.lg0fhwtmd3el@localhost.databox    | > node server.js
app-light-graph.1.d7gjw6ez14tr@localhost.databox    | > node server.js
app-light-graph.1.xobwwbnyass5@localhost.databox    | 
app-light-graph.1.xobwwbnyass5@localhost.databox    | > app-light-graph@0.1.0 start /
app-light-graph.1.u4nc7lxylipd@localhost.databox    | > app-light-graph@0.1.0 start /
app-light-graph.1.lg0fhwtmd3el@localhost.databox    | 
app-light-graph.1.d7gjw6ez14tr@localhost.databox    | 
app-light-graph.1.d7gjw6ez14tr@localhost.databox    | npm info lifecycle app-light-graph@0.1.0~prestart: app-light-graph@0.1.0
app-light-graph.1.xobwwbnyass5@localhost.databox    | > node server.js
app-light-graph.1.u4nc7lxylipd@localhost.databox    | > node server.js
app-light-graph.1.lg0fhwtmd3el@localhost.databox    | npm info lifecycle app-light-graph@0.1.0~prestart: app-light-graph@0.1.0
app-light-graph.1.lg0fhwtmd3el@localhost.databox    | npm info lifecycle app-light-graph@0.1.0~start: app-light-graph@0.1.0
app-light-graph.1.d7gjw6ez14tr@localhost.databox    | npm info lifecycle app-light-graph@0.1.0~start: app-light-graph@0.1.0
app-light-graph.1.xobwwbnyass5@localhost.databox    | 
app-light-graph.1.u4nc7lxylipd@localhost.databox    | 
app-light-graph.1.u4nc7lxylipd@localhost.databox    | url.js:102
app-light-graph.1.lg0fhwtmd3el@localhost.databox    | url.js:102
app-light-graph.1.d7gjw6ez14tr@localhost.databox    | url.js:102
app-light-graph.1.xobwwbnyass5@localhost.databox    | url.js:102
app-light-graph.1.xobwwbnyass5@localhost.databox    |     throw new TypeError('Parameter "url" must be a string, not ' + typeof url);
app-light-graph.1.u4nc7lxylipd@localhost.databox    |     throw new TypeError('Parameter "url" must be a string, not ' + typeof url);
app-light-graph.1.lg0fhwtmd3el@localhost.databox    |     throw new TypeError('Parameter "url" must be a string, not ' + typeof url);
app-light-graph.1.d7gjw6ez14tr@localhost.databox    |     throw new TypeError('Parameter "url" must be a string, not ' + typeof url);
app-light-graph.1.d7gjw6ez14tr@localhost.databox    |     ^
app-light-graph.1.xobwwbnyass5@localhost.databox    |     ^
app-light-graph.1.u4nc7lxylipd@localhost.databox    |     ^
app-light-graph.1.lg0fhwtmd3el@localhost.databox    |     ^
app-light-graph.1.lg0fhwtmd3el@localhost.databox    | 
app-light-graph.1.d7gjw6ez14tr@localhost.databox    | 
app-light-graph.1.xobwwbnyass5@localhost.databox    | 
app-light-graph.1.u4nc7lxylipd@localhost.databox    | 
app-light-graph.1.u4nc7lxylipd@localhost.databox    | TypeError: Parameter "url" must be a string, not undefined
app-light-graph.1.lg0fhwtmd3el@localhost.databox    | TypeError: Parameter "url" must be a string, not undefined
app-light-graph.1.d7gjw6ez14tr@localhost.databox    | TypeError: Parameter "url" must be a string, not undefined
app-light-graph.1.xobwwbnyass5@localhost.databox    | TypeError: Parameter "url" must be a string, not undefined
app-light-graph.1.xobwwbnyass5@localhost.databox    |     at Url.parse (url.js:102:11)
app-light-graph.1.u4nc7lxylipd@localhost.databox    |     at Url.parse (url.js:102:11)
app-light-graph.1.lg0fhwtmd3el@localhost.databox    |     at Url.parse (url.js:102:11)
app-light-graph.1.d7gjw6ez14tr@localhost.databox    |     at Url.parse (url.js:102:11)
app-light-graph.1.d7gjw6ez14tr@localhost.databox    |     at Object.urlParse [as parse] (url.js:96:5)
app-light-graph.1.xobwwbnyass5@localhost.databox    |     at Object.urlParse [as parse] (url.js:96:5)
app-light-graph.1.u4nc7lxylipd@localhost.databox    |     at Object.urlParse [as parse] (url.js:96:5)
app-light-graph.1.lg0fhwtmd3el@localhost.databox    |     at Object.urlParse [as parse] (url.js:96:5)
app-light-graph.1.lg0fhwtmd3el@localhost.databox    |     at Object.<anonymous> (/server.js:15:67)
app-light-graph.1.d7gjw6ez14tr@localhost.databox    |     at Object.<anonymous> (/server.js:15:67)
app-light-graph.1.xobwwbnyass5@localhost.databox    |     at Object.<anonymous> (/server.js:15:67)
app-light-graph.1.u4nc7lxylipd@localhost.databox    |     at Object.<anonymous> (/server.js:15:67)
app-light-graph.1.u4nc7lxylipd@localhost.databox    |     at Module._compile (module.js:569:30)
app-light-graph.1.lg0fhwtmd3el@localhost.databox    |     at Module._compile (module.js:569:30)
app-light-graph.1.d7gjw6ez14tr@localhost.databox    |     at Module._compile (module.js:569:30)
app-light-graph.1.xobwwbnyass5@localhost.databox    |     at Module._compile (module.js:569:30)
app-light-graph.1.xobwwbnyass5@localhost.databox    |     at Object.Module._extensions..js (module.js:580:10)
app-light-graph.1.u4nc7lxylipd@localhost.databox    |     at Object.Module._extensions..js (module.js:580:10)
app-light-graph.1.lg0fhwtmd3el@localhost.databox    |     at Object.Module._extensions..js (module.js:580:10)
app-light-graph.1.d7gjw6ez14tr@localhost.databox    |     at Object.Module._extensions..js (module.js:580:10)
app-light-graph.1.d7gjw6ez14tr@localhost.databox    |     at Module.load (module.js:503:32)
app-light-graph.1.xobwwbnyass5@localhost.databox    |     at Module.load (module.js:503:32)
app-light-graph.1.u4nc7lxylipd@localhost.databox    |     at Module.load (module.js:503:32)
app-light-graph.1.lg0fhwtmd3el@localhost.databox    |     at Module.load (module.js:503:32)
app-light-graph.1.lg0fhwtmd3el@localhost.databox    |     at tryModuleLoad (module.js:466:12)
app-light-graph.1.d7gjw6ez14tr@localhost.databox    |     at tryModuleLoad (module.js:466:12)
app-light-graph.1.xobwwbnyass5@localhost.databox    |     at tryModuleLoad (module.js:466:12)
app-light-graph.1.u4nc7lxylipd@localhost.databox    |     at tryModuleLoad (module.js:466:12)
app-light-graph.1.u4nc7lxylipd@localhost.databox    |     at Function.Module._load (module.js:458:3)
app-light-graph.1.lg0fhwtmd3el@localhost.databox    |     at Function.Module._load (module.js:458:3)
app-light-graph.1.d7gjw6ez14tr@localhost.databox    |     at Function.Module._load (module.js:458:3)
app-light-graph.1.xobwwbnyass5@localhost.databox    |     at Function.Module._load (module.js:458:3)
app-light-graph.1.xobwwbnyass5@localhost.databox    |     at Function.Module.runMain (module.js:605:10)
app-light-graph.1.u4nc7lxylipd@localhost.databox    |     at Function.Module.runMain (module.js:605:10)
app-light-graph.1.lg0fhwtmd3el@localhost.databox    |     at Function.Module.runMain (module.js:605:10)
app-light-graph.1.d7gjw6ez14tr@localhost.databox    |     at Function.Module.runMain (module.js:605:10)
app-light-graph.1.d7gjw6ez14tr@localhost.databox    |     at startup (bootstrap_node.js:158:16)
app-light-graph.1.xobwwbnyass5@localhost.databox    |     at startup (bootstrap_node.js:158:16)
app-light-graph.1.u4nc7lxylipd@localhost.databox    |     at startup (bootstrap_node.js:158:16)
app-light-graph.1.lg0fhwtmd3el@localhost.databox    |     at startup (bootstrap_node.js:158:16)
app-light-graph.1.lg0fhwtmd3el@localhost.databox    | npm info lifecycle app-light-graph@0.1.0~start: Failed to exec start script
app-light-graph.1.d7gjw6ez14tr@localhost.databox    | npm info lifecycle app-light-graph@0.1.0~start: Failed to exec start script
app-light-graph.1.xobwwbnyass5@localhost.databox    | npm info lifecycle app-light-graph@0.1.0~start: Failed to exec start script
app-light-graph.1.u4nc7lxylipd@localhost.databox    | npm info lifecycle app-light-graph@0.1.0~start: Failed to exec start script
app-light-graph.1.u4nc7lxylipd@localhost.databox    | npm ERR! code ELIFECYCLE
app-light-graph.1.lg0fhwtmd3el@localhost.databox    | npm ERR! code ELIFECYCLE
app-light-graph.1.d7gjw6ez14tr@localhost.databox    | npm ERR! code ELIFECYCLE
app-light-graph.1.xobwwbnyass5@localhost.databox    | npm ERR! code ELIFECYCLE
app-light-graph.1.xobwwbnyass5@localhost.databox    | npm ERR! errno 1
app-light-graph.1.u4nc7lxylipd@localhost.databox    | npm ERR! errno 1
app-light-graph.1.lg0fhwtmd3el@localhost.databox    | npm ERR! errno 1
app-light-graph.1.d7gjw6ez14tr@localhost.databox    | npm ERR! errno 1
app-light-graph.1.d7gjw6ez14tr@localhost.databox    | npm ERR! app-light-graph@0.1.0 start: `node server.js`
app-light-graph.1.xobwwbnyass5@localhost.databox    | npm ERR! app-light-graph@0.1.0 start: `node server.js`
app-light-graph.1.u4nc7lxylipd@localhost.databox    | npm ERR! app-light-graph@0.1.0 start: `node server.js`
app-light-graph.1.lg0fhwtmd3el@localhost.databox    | npm ERR! app-light-graph@0.1.0 start: `node server.js`
app-light-graph.1.lg0fhwtmd3el@localhost.databox    | npm ERR! Exit status 1
app-light-graph.1.d7gjw6ez14tr@localhost.databox    | npm ERR! Exit status 1
app-light-graph.1.xobwwbnyass5@localhost.databox    | npm ERR! Exit status 1
app-light-graph.1.u4nc7lxylipd@localhost.databox    | npm ERR! Exit status 1
app-light-graph.1.u4nc7lxylipd@localhost.databox    | npm ERR! 
app-light-graph.1.lg0fhwtmd3el@localhost.databox    | npm ERR! 
app-light-graph.1.d7gjw6ez14tr@localhost.databox    | npm ERR! 
app-light-graph.1.xobwwbnyass5@localhost.databox    | npm ERR! 
app-light-graph.1.xobwwbnyass5@localhost.databox    | npm ERR! Failed at the app-light-graph@0.1.0 start script.
app-light-graph.1.u4nc7lxylipd@localhost.databox    | npm ERR! Failed at the app-light-graph@0.1.0 start script.
app-light-graph.1.lg0fhwtmd3el@localhost.databox    | npm ERR! Failed at the app-light-graph@0.1.0 start script.
app-light-graph.1.d7gjw6ez14tr@localhost.databox    | npm ERR! Failed at the app-light-graph@0.1.0 start script.
app-light-graph.1.d7gjw6ez14tr@localhost.databox    | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
app-light-graph.1.xobwwbnyass5@localhost.databox    | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
app-light-graph.1.u4nc7lxylipd@localhost.databox    | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
app-light-graph.1.lg0fhwtmd3el@localhost.databox    | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
app-light-graph.1.lg0fhwtmd3el@localhost.databox    | 
app-light-graph.1.d7gjw6ez14tr@localhost.databox    | 
app-light-graph.1.xobwwbnyass5@localhost.databox    | 
app-light-graph.1.u4nc7lxylipd@localhost.databox    | 
app-light-graph.1.u4nc7lxylipd@localhost.databox    | npm ERR! A complete log of this run can be found in:
app-light-graph.1.lg0fhwtmd3el@localhost.databox    | npm ERR! A complete log of this run can be found in:
app-light-graph.1.d7gjw6ez14tr@localhost.databox    | npm ERR! A complete log of this run can be found in:
app-light-graph.1.xobwwbnyass5@localhost.databox    | npm ERR! A complete log of this run can be found in:
app-light-graph.1.xobwwbnyass5@localhost.databox    | npm ERR!     /root/.npm/_logs/2017-07-25T10_09_40_741Z-debug.log
app-light-graph.1.u4nc7lxylipd@localhost.databox    | npm ERR!     /root/.npm/_logs/2017-07-25T10_09_21_174Z-debug.log
app-light-graph.1.lg0fhwtmd3el@localhost.databox    | npm ERR!     /root/.npm/_logs/2017-07-25T10_09_11_695Z-debug.log
app-light-graph.1.d7gjw6ez14tr@localhost.databox    | npm ERR!     /root/.npm/_logs/2017-07-25T10_09_30_903Z-debug.log
[root@localhost databox]#

**Comment by yousefamar** [comment]
Hi @laelaeaung, during the SLA process, did you bind the datasource exposed by the driver to this app? It should be a drop-down in the bottom before you hit launch.

The cause of this crash, for posterity, is that in your case, the environment variable `DATASOURCE_DS_light` is undefined, so `DATASOURCE_DS_light.href` is also undefined [here](https://github.com/me-box/app-light-graph/blob/master/server.js#L15), and `url.parse` complains. Ideally we should have Databox refuse to start an app if the required sources aren't bound, or else the apps should indicate that they won't function due to missing datasources (because of permissions or otherwise) instead of just crashing, but that is not yet the case.

**Comment by tsh-box** [comment]
Hi! @yousefamar , I have running the driver-sensinkit but not yet bind with datasource that means the data from smart phone,is it right?

**Comment by yousefamar** [comment]
Yes, so when you click the app to launch it, it should give you an "SLA" page first, and in the bottom, it should ask you what to bind. That way you can connect the driver's store to the app.

**Comment by tsh-box** [comment]
OK,firstly i need to bind the datasource with driver(driver-sensinkit) and then app install will work,Is it right? 
Sorry for my confirm message again. :)
Thanks you,

**Comment by yousefamar** [comment]
No I'm talking about between store and app. The terminology is a bit confusing here, since those are also called datasources. When you install an app, there should be the view where you can control permissions, and towards the bottom you can add these datasources.

**Comment by tsh-box** [comment]
I want to successfully install app-light-graph what should I do ,Could you tell me,please?

**Comment by yousefamar** [comment]
Screenshot kindly provided by @jptmoore, I've circled the part I mean in red:

![untitled](https://user-images.githubusercontent.com/999235/28611766-24135c7e-71ed-11e7-9aa8-3018b3da78a7.png)

**Comment by tsh-box** [comment]
yes,me too light is unbound state.

**Comment by yousefamar** [comment]
If you click it does it let you select the source from the driver you have running? Since if it's unset, that's what made the app crash before.

**Comment by tsh-box** [comment]
hi!

![1111](https://user-images.githubusercontent.com/29420329/28657589-d1528bc6-72e2-11e7-8964-3b3e161169a1.png)

So ,I stopped the databox with ./stopDatabox.sh and then executed ./startDatabox.sh and installed the driver-sensingkit .When I confirmed the driver-sensingkit-store-json from Stores menu tab,Invalid API key is shown as following.

![000](https://user-images.githubusercontent.com/29420329/28657823-a7f819a2-72e3-11e7-94c2-632195a0a923.png)

Why does occurs this error ?Yesterday ,there was no error .

Thank you,

**Comment by yousefamar** [comment]
Hi @laelaeaung, are you running in dev mode? Yesterday I made some changes to the arbiter, and it could be that you're using an old build. Apologies for the inconvenience. Could you first try to turn everything off and on again, by running `./stopDatabox.sh` and `./startDatabox.sh`?

Were you able to bind the source yesterday?

**Comment by yousefamar** [comment]
> So ,I stopped the databox with ./stopDatabox.sh and then executed ./startDatabox.sh and installed the driver-sensingkit .

If you've already done that since then, could you try updating the local image of databox arbiter by running `docker pull databoxsystems/arbiter`?

**Comment by tsh-box** [comment]
Yesterday,I cannot be bind with source.
I executed 'docker pull databoxsystems/arbiter' 

![000](https://user-images.githubusercontent.com/29420329/28658574-f75cae42-72e6-11e7-901b-afc55d18f948.png)

**Comment by yousefamar** [comment]
Ok, now could you restart Databox, and make sure the driver and the store are stopped, then start the driver and app, and see if you still can't bind?

**Comment by tsh-box** [comment]
How to restart Databox?

**Comment by yousefamar** [comment]
I mean ./stopDatabox.sh && ./startDatabox.sh.

**Comment by tsh-box** [comment]
I restarted databox and then reinstall the driver(driver-sensingkit ) and app(app-light-grap).It is still cannot be bound.Is it need to connect data from andriod app (eg.databox-source-mobile-debug.apk) ?

**Comment by Toshbrown** [comment]
Have you connected the phone?

**Comment by tsh-box** [comment]
not yet connected,I have no andriod phone, Can I use the andriod os from the virtualBox.

**Comment by yousefamar** [comment]
Do you still get `Invalid API key/token`?

**Comment by tsh-box** [comment]
Yes,I still get Invalid API key/token.Now I am install with dev mode like './startdataboc.sh dev' ,Is this error concern about with dev mode?I cannot install with dev mode because memory space is not enough.

**Comment by Toshbrown** [comment]
Can you restart and try again, things should be fixed now. 

I'm not sure if the app will work in the Android VM.

I'm hopefully adding some new apps in the next day or two, which don't need any external hardware.

**Comment by yousefamar** [comment]
I think in theory it should work, but the app UI might give you the wrong IP. You might have to use the VirtualBox Guest's IP, and you might have to configure some network settings too.

Edit: not to mention that of course the emulator does not have real sensors.

**Comment by tsh-box** [comment]
@Toshbrown ,
Yes,I can restart and try again.Tomorrow I will test with andriod phone :)
I am looking forward to your new apps  :)
Thanks you

**Comment by tsh-box** [comment]
@yousefamar ,
Ok,Tomorrow I will test with the VirtualBox Guest's IP 
If any problem,I will ask you again  :)
Thank you.

**Comment by Toshbrown** [comment]
I have added app-os-monitor to enable testing without any extra hardware or external accounts

**Comment by tsh-box** [comment]
Hello!Tosh
Thanks you for your ready made app for test.
Today I used the latest source code from me/databox(master branch).I have installed driver-os-monitor and I attached the figure that is installing app-os-monitor

![000](https://user-images.githubusercontent.com/29420329/28703451-18802082-739f-11e7-984f-f6451ad65c28.png)


now can be selected the datasource and when click install button ,there is no working ,I attached the console figure 

![1111](https://user-images.githubusercontent.com/29420329/28703568-0a6ee518-73a0-11e7-91e6-60cccf955f68.png)

**Comment by tsh-box** [comment]
I did it.  :)
The app-os-monitor can test without any extra hardware,Thanks you.
![000](https://user-images.githubusercontent.com/29420329/28707578-dea6664a-73b3-11e7-96dd-014fdfbb7aea.png)

 For Other app, Firstly,driver installation needs and then this driver must join with data(eg; light,GPS) from devices by uploading json,etc;,Is it right?

**Comment by yousefamar** [comment]
> For Other app, previously,driver installation and it must join with data(eg; light,GPS) from devices ,Is it right?

:+1:

**Comment by tsh-box** [comment]
:)
thanks you.
Export service can be use in databox?

**Comment by Toshbrown** [comment]
Yes, I believe that the export service is functional. It's not been heavily tested though. 

As you have it working I'm going to close this issue now. Feel free open a new one if you find anything else.

**Comment by tsh-box** [comment]
Thank you,
