### ISSUE TITLE
databox_syslog error

### ISSUE THREAD

**Issue by tsh-box** [me-box/databox#71]
In Stores menu tab,databox_syslog does not work .

![000](https://user-images.githubusercontent.com/29420329/28608851-2db20f5c-721d-11e7-8698-16ca3748db27.png)

![1111](https://user-images.githubusercontent.com/29420329/28608856-319f1f60-721d-11e7-9f6f-ad3dd02accc2.png)

**Comment by Toshbrown** [comment]
This is expected, syslog has no UI yet :-)

**Comment by tsh-box** [comment]
Thank you :)
