### ISSUE TITLE
databox_export-service does not work?

### ISSUE THREAD

**Issue by tsh-box** [me-box/databox#73]
Hi,
In SYSTEM tab menu from databox UI,the status of the databox_export-service is running but click it ,the following error is shown 

![1111](https://user-images.githubusercontent.com/29420329/28764329-b6203ebe-75ff-11e7-95d4-d520ee9bd0e9.png)

**Comment by Toshbrown** [comment]
The export-service has no ui. 

An example of its use can be seen here https://github.com/me-box/app-twitter-sentiment/blob/master/src/main.js#L133
