### ISSUE TITLE
Driver repeat installation issue

### ISSUE THREAD

**Issue by pooyadav** [me-box/databox#74]
There should a mechanism to stop the installation of already installed driver or app again. Currently, from UI there is no way to get back (or stop) once install button is clicked. In background an error is thrown, but I think there should be some way of graceful error-handling mechanism for this issue.

**Comment by Toshbrown** [comment]
Agreed. 

I think @ktg is picking this up in #11

**Comment by Toshbrown** [comment]
fixed in https://github.com/me-box/core-container-manager/commit/7af22eb7954cc63795b7525783160c3f85ad8b61 by @ktg
