### ISSUE TITLE
How can I Test the export service is working?

### ISSUE THREAD

**Issue by tsh-box** [me-box/databox#75]
How can I test that the export service  is working in databox?Please Could you help me?

**Comment by yousefamar** [comment]
I just put https://export.amar.io/ back up. Perhaps you could try to export to that URL and see if your requests log on the page?

To export like [this](https://github.com/me-box/app-twitter-sentiment/blob/master/src/main.js#L133) make sure your manifest lists [the correct permissions](https://github.com/me-box/app-twitter-sentiment/blob/master/databox-manifest.json#L79-L84).

**Comment by tsh-box** [comment]
I have searched documents about the export service.and then i seen that the following one 

Method   : POST
URL      : /export or /lp/export
Parameter: JSON object that has the format {id: <request id>, uri: <destination url>, data: <export data>}
Response : JSON object with the format {id: <request id>, state: <request state>, ext_response: <response>}


I try it by using REST client but does not effective because of i didn't known the json of the data format(
eg; id: <>,uri: and data).

**Comment by Toshbrown** [comment]
Can you tell us what you are trying to achieve? 

Also, I'm happy to take a look at your code if it is somewhere I can access it.

**Comment by tsh-box** [comment]
I want to test the export service.

I tried with Rest Client 
![000](https://user-images.githubusercontent.com/29420329/28916069-f33f19b8-787b-11e7-9fc3-61cb0906f131.png)

**Comment by tsh-box** [comment]
@yousefamar 
thanks you,for your reply
I will try it.Is is need to install the app(app-twitter-sentiment)?

**Comment by pooyadav** [comment]
![](https://user-images.githubusercontent.com/29420329/28916069-f33f19b8-787b-11e7-9fc3-61cb0906f131.png)
I think Header for the post  will be 'x-api-key' =`< token received from arbitor>`

**Comment by Toshbrown** [comment]
The export service exists to let apps send data back to their writers. Testing it outside of databox does not make much sense. 

To test it you will need to write an app, with the correct permissions run it within databox and have an external url to send the data to.

**Comment by tsh-box** [comment]
@Toshbrown ,Could I use the already existed app(eg; app-os-monitor) to test the export service?
The export service is to emit the data of app from databox,Is it true?
Is there database(DB) anything about databox?

**Comment by tsh-box** [comment]
@pooyadav, There is no request header like 'x-api-key' in Rest client .

**Comment by Toshbrown** [comment]
@laelaeaung yes app-os-monitor could be modified to use the export service 

The app-twitter-sentiment already has an example of how it's done see: 

https://github.com/me-box/app-twitter-sentiment/blob/master/databox-manifest.json#L79
https://github.com/me-box/app-twitter-sentiment/blob/master/src/main.js#L133

**Comment by tsh-box** [comment]
Thank you,
I will test by using app-twitter-sentiment .

**Comment by Toshbrown** [comment]
Sounds like a plan. Closing
