### ISSUE TITLE
driver-twitter installation exited

### ISSUE THREAD

**Issue by tsh-box** [me-box/databox#76]
I installed the driver-twitter but installation is exited .

![000](https://user-images.githubusercontent.com/29420329/29009102-32398d60-7b5b-11e7-9c77-acea16cd3641.png)

**Comment by tsh-box** [comment]
Now it is work :)  thank you

**Comment by Toshbrown** [comment]
Good stuff, you will need to follow the instructions to register your API keys here (https://github.com/me-box/driver-twitter/blob/master/README.md)  before it will get any data.
