### ISSUE TITLE
app-twitter-sentiment 

### ISSUE THREAD

**Issue by tsh-box** [me-box/databox#77]
I have installed the driver-twitter and registered the API keys by referencing(https://github.com/me-box/driver-twitter/blob/master/README.md).
And then,I installed app-twitter-sentiment by selecting datasources

![1111](https://user-images.githubusercontent.com/29420329/29020070-c0ea81f0-7b9b-11e7-8674-a370e089de5e.png)

it take too long of installing and then when I confirmed the terminal ,I seen the following message

![000](https://user-images.githubusercontent.com/29420329/29020124-ef449dce-7b9b-11e7-84c2-1e5e85be1c4f.png)

**Comment by Toshbrown** [comment]
Fix incoming, thanks for reporting this.

**Comment by tsh-box** [comment]
Now I think, it is works ,thanks you.The following message is shown when click it,Is it OK?
{
    "tweet": "No tweets received yet ...."
}

**Comment by Toshbrown** [comment]
Yeah, it can take a while for twitter to start sending data. 

docker service logs driver-twitter 

Should help you debug any problems you should see "Saving data:: [some ID] [some tweet txt]" if its working

**Comment by tsh-box** [comment]
I have saved the access token key in driver-twitter and datasources also added when installed app-twitter.

![000](https://user-images.githubusercontent.com/29420329/29057328-93d38de8-7c44-11e7-93f1-0e068cedc178.png)

![1111](https://user-images.githubusercontent.com/29420329/29057338-9c957f2c-7c44-11e7-8556-a2244c96e101.png)

I added a post in twitter and also like.
I am waiting for a while to receive data from twitter but data could not see in databox.
Is it need anything to do?

**Comment by Toshbrown** [comment]
Take a look at : 

docker service logs driver-twitter

**Comment by tsh-box** [comment]
[databox@localhost ~]$ docker service logs driver-twitter
driver-twitter.1.mmflg4bbn7zt@localhost.databox    | npm info it worked if it ends with ok
driver-twitter.1.mmflg4bbn7zt@localhost.databox    | npm info using npm@5.3.0
driver-twitter.1.mmflg4bbn7zt@localhost.databox    | npm info using node@v8.2.1
driver-twitter.1.mmflg4bbn7zt@localhost.databox    | npm info lifecycle driver-twitter@1.0.0~prestart: driver-twitter@1.0.0
driver-twitter.1.mmflg4bbn7zt@localhost.databox    | npm info lifecycle driver-twitter@1.0.0~start: driver-twitter@1.0.0
driver-twitter.1.mmflg4bbn7zt@localhost.databox    | 
driver-twitter.1.mmflg4bbn7zt@localhost.databox    | > driver-twitter@1.0.0 start /
driver-twitter.1.mmflg4bbn7zt@localhost.databox    | > node ./src/main.js
driver-twitter.1.mmflg4bbn7zt@localhost.databox    | 
driver-twitter.1.mmflg4bbn7zt@localhost.databox    | [waitForStoreStatus] Retrying in 1s...
driver-twitter.1.mmflg4bbn7zt@localhost.databox    | Target driver-twitter-store-json has not registered itself for arbitering
driver-twitter.1.mmflg4bbn7zt@localhost.databox    | [waitForStoreStatus] Retrying in 1s...
driver-twitter.1.mmflg4bbn7zt@localhost.databox    | Target driver-twitter-store-json has not registered itself for arbitering
driver-twitter.1.mmflg4bbn7zt@localhost.databox    | DS Added https://driver-twitter-store-json:8080 undefined undefined
driver-twitter.1.mmflg4bbn7zt@localhost.databox    | [getSettings] using defaults  No setting found.  Using ---->  { hashTags: [ '#raspberrypi', '#mozfest', '#databox', '#iot', '#NobelPrize' ] }
driver-twitter.1.mmflg4bbn7zt@localhost.databox    | [Creating server] and twitter Auth
driver-twitter.1.mmflg4bbn7zt@localhost.databox    | Twitter Auth
driver-twitter.1.mmflg4bbn7zt@localhost.databox    | [ERROR] Error: Twit config must include `consumer_key` when using user auth.
driver-twitter.1.mmflg4bbn7zt@localhost.databox    |     at /node_modules/twit/lib/twitter.js:491:13
driver-twitter.1.mmflg4bbn7zt@localhost.databox    |     at Array.forEach (native)
driver-twitter.1.mmflg4bbn7zt@localhost.databox    |     at Twitter._validateConfigOrThrow (/node_modules/twit/lib/twitter.js:488:17)
driver-twitter.1.mmflg4bbn7zt@localhost.databox    |     at new Twitter (/node_modules/twit/lib/twitter.js:58:8)
driver-twitter.1.mmflg4bbn7zt@localhost.databox    |     at Promise (/src/twitter.js:21:13)
driver-twitter.1.mmflg4bbn7zt@localhost.databox    |     at Promise (<anonymous>)
driver-twitter.1.mmflg4bbn7zt@localhost.databox    |     at Object.connect (/src/twitter.js:20:14)
driver-twitter.1.mmflg4bbn7zt@localhost.databox    |     at databox.waitForStoreStatus.then.then.then (/src/main.js:198:35)
driver-twitter.1.mmflg4bbn7zt@localhost.databox    |     at <anonymous>
driver-twitter.1.mmflg4bbn7zt@localhost.databox    |     at process._tickCallback (internal/process/next_tick.js:188:7)
driver-twitter.1.mmflg4bbn7zt@localhost.databox    | [getSettings] using defaults  No setting found.  Using ---->  { hashTags: [ '#raspberrypi', '#mozfest', '#databox', '#iot', '#NobelPrize' ] }
driver-twitter.1.mmflg4bbn7zt@localhost.databox    | [/ui render]
driver-twitter.1.mmflg4bbn7zt@localhost.databox    | [getSettings] using defaults  No setting found.  Using ---->  { hashTags: [ '#raspberrypi', '#mozfest', '#databox', '#iot', '#NobelPrize' ],
driver-twitter.1.mmflg4bbn7zt@localhost.databox    |   _locals: {} }
driver-twitter.1.mmflg4bbn7zt@localhost.databox    | [/ui render]
driver-twitter.1.mmflg4bbn7zt@localhost.databox    | [getSettings] using defaults  No setting found.  Using ---->  { hashTags: [ '#raspberrypi', '#mozfest', '#databox', '#iot', '#NobelPrize' ],
driver-twitter.1.mmflg4bbn7zt@localhost.databox    |   _locals: {} }
driver-twitter.1.mmflg4bbn7zt@localhost.databox    | [setCreds] Error  TypeError: Cannot read property 'consumer_key' of undefined
driver-twitter.1.mmflg4bbn7zt@localhost.databox    |     at getSettings.then (/src/main.js:60:40)
driver-twitter.1.mmflg4bbn7zt@localhost.databox    |     at <anonymous>
driver-twitter.1.mmflg4bbn7zt@localhost.databox    |     at process._tickCallback (internal/process/next_tick.js:188:7)
driver-twitter.1.mmflg4bbn7zt@localhost.databox    | [getSettings] using defaults  No setting found.  Using ---->  { hashTags: [ '#raspberrypi', '#mozfest', '#databox', '#iot', '#NobelPrize' ],
driver-twitter.1.mmflg4bbn7zt@localhost.databox    |   _locals: {} }
driver-twitter.1.mmflg4bbn7zt@localhost.databox    | [/ui render]
driver-twitter.1.mmflg4bbn7zt@localhost.databox    | [getSettings] using defaults  No setting found.  Using ---->  { hashTags: [ '#raspberrypi', '#mozfest', '#databox', '#iot', '#NobelPrize' ],
driver-twitter.1.mmflg4bbn7zt@localhost.databox    |   _locals: {} }
driver-twitter.1.mmflg4bbn7zt@localhost.databox    | [/ui render]
[databox@localhost ~]$

**Comment by Toshbrown** [comment]
I have just pushed a change to fix this.
