### ISSUE TITLE
Databox system has a database?

### ISSUE THREAD

**Issue by tsh-box** [me-box/databox#78]
Hello,
Have database in databox system?If exist,Could you tell me the place of document about database?
Thank you,

**Comment by Toshbrown** [comment]
Are the early implementations of data stores for databox:

https://github.com/me-box/store-json

https://github.com/me-box/store-timeseries

**Comment by tsh-box** [comment]
Thank you for your reply,And I have one question.
I have PPM server that has a function that can control the provision of data.
I want to join the PPM server and databox system ,Is is possible?

**Comment by Toshbrown** [comment]
Wahts a PPM server?

**Comment by tsh-box** [comment]
PPM means Privacy Policy Manager,
There is a function to control the provison of data to third user.
it can judge(For example, do not submit this information to a third party.)

**Comment by Toshbrown** [comment]
sounds interesting, 

What are you trying to achieve?

 This sounds like an extension of the export service. Do you have any documentation I could take a look at?

**Comment by tsh-box** [comment]
Thanks you,
Now I drafted the design,Please look at it,tomorrow I will confirm about my draft to my supervisor.

**Comment by Toshbrown** [comment]
I see, looks like you will need to modify the export service to achieve your goal. This should be possible. 

Who is your supervisor, where are are you working?

**Comment by tsh-box** [comment]
I am from Myanmar but now I am internship at KDDI in Tokyo.
My supervisor is Satou sama.

**Comment by tsh-box** [comment]
Hi,
app-twitter-sentiment and driver-twitter is working.It receive the info data from twitter .

![000](https://user-images.githubusercontent.com/29420329/29152026-d8b2ccf4-7dbf-11e7-80e0-e1bb9a91ae5f.png)

And export to the https://export.amar.io/
but it seems does not contain data,Is it OK?
![1111](https://user-images.githubusercontent.com/29420329/29152193-fe17ce44-7dc0-11e7-9710-8f0182e717cf.png)

**Comment by Toshbrown** [comment]
Whats the output of 

docker service logs databox_export-service

**Comment by tsh-box** [comment]
[databox@localhost ~]$ docker service logs databox_export-service 
databox_export-service.1.lum2y1ooa8ff@localhost.databox    | service: [ERROR] [macaroon] no secret from arbiter: Invalid API key
[databox@localhost ~]$

**Comment by Toshbrown** [comment]
This should be resolved now https://github.com/me-box/core-export-service/issues/25 has been resolved
