### ISSUE TITLE
driver-sensingkit cannot join with android phone 

### ISSUE THREAD

**Issue by tsh-box** [me-box/databox#79]
Hi ,
I have installed the driver-sensingkit in vmbox(centos7).
And I installed the vmbox(andriod os) on the centos7.
In this Andriod os,I installed the databox-source-mobile-debug.apk and run it.
After port forwarding  the andriod os network(10.0.2.15:5555),I confirmed this port in the centos7 ,It is ok.
So I used 10.0.2.15:5555 in driver-sensingkit UI.But It does not work .
I confirmed the logs of driver-sensingkit.

[databox@localhost ~]$ docker service logs driver-sensingkit
driver-sensingkit.1.ptzh6op5qddc@localhost.databox    | npm info it worked if it ends with ok
driver-sensingkit.1.ptzh6op5qddc@localhost.databox    | npm info using npm@5.3.0
driver-sensingkit.1.ptzh6op5qddc@localhost.databox    | npm info using node@v8.2.0
driver-sensingkit.1.ptzh6op5qddc@localhost.databox    | npm info lifecycle driver-sensingkit@0.1.0~prestart: driver-sensingkit@0.1.0
driver-sensingkit.1.ptzh6op5qddc@localhost.databox    | npm info lifecycle driver-sensingkit@0.1.0~start: driver-sensingkit@0.1.0
driver-sensingkit.1.ptzh6op5qddc@localhost.databox    | 
driver-sensingkit.1.ptzh6op5qddc@localhost.databox    | > driver-sensingkit@0.1.0 start /
driver-sensingkit.1.ptzh6op5qddc@localhost.databox    | > node main.js
driver-sensingkit.1.ptzh6op5qddc@localhost.databox    | 
driver-sensingkit.1.ptzh6op5qddc@localhost.databox    | [waitForStoreStatus] Retrying in 1s...
driver-sensingkit.1.ptzh6op5qddc@localhost.databox    | Target driver-sensingkit-store-json has not registered itself for arbitering
driver-sensingkit.1.ptzh6op5qddc@localhost.databox    | [waitForStoreStatus] Retrying in 1s...
driver-sensingkit.1.ptzh6op5qddc@localhost.databox    | Target driver-sensingkit-store-json has not registered itself for arbitering
[databox@localhost ~]$ 

Thanks you,

**Comment by Toshbrown** [comment]
This sounds like a networking issue. 

The Android phone and the machine running databox need to be able to directly communicate.  Without complex networking setups, this usually requires that they are on the same network.
