### ISSUE TITLE
store json for driver does not store data

### ISSUE THREAD

**Issue by tsh-box** [me-box/databox#82]
Hello!
I restarted the databox and then installed the driver-os-monitor.But driver-os-monitor-store-json has an error that is "Cannot GET /driver-os-monitor-store-json/cat" .

I pasted the logs of driver-os-monitor-store-json as following as;

[databox@localhost databox-master]$ docker service logs driver-os-monitor-store-json 
driver-os-monitor-store-json.1.yjndtygwa795@localhost.databox    | 
driver-os-monitor-store-json.1.yjndtygwa795@localhost.databox    | > store-json@1.0.0 prestart /
driver-os-monitor-store-json.1.yjndtygwa795@localhost.databox    | > mongod --dbpath database --fork --logpath /dev/null --wiredTigerEngineConfigString="cache_size=50M"
driver-os-monitor-store-json.1.yjndtygwa795@localhost.databox    | 
driver-os-monitor-store-json.1.yjndtygwa795@localhost.databox    | 2017-08-24T04:43:11.313+0000 I STORAGE  [main] Engine custom option: cache_size=50M
driver-os-monitor-store-json.1.yjndtygwa795@localhost.databox    | about to fork child process, waiting until server is ready for connections.
driver-os-monitor-store-json.1.yjndtygwa795@localhost.databox    | forked process: 22
driver-os-monitor-store-json.1.yjndtygwa795@localhost.databox    | child process started successfully, parent exiting
driver-os-monitor-store-json.1.yjndtygwa795@localhost.databox    | 
driver-os-monitor-store-json.1.yjndtygwa795@localhost.databox    | > store-json@1.0.0 start /
driver-os-monitor-store-json.1.yjndtygwa795@localhost.databox    | > node ./src/main.js
driver-os-monitor-store-json.1.yjndtygwa795@localhost.databox    | 
driver-os-monitor-store-json.1.yjndtygwa795@localhost.databox    | [databox-request] https://arbiter:8080/store/secret
driver-os-monitor-store-json.1.yjndtygwa795@localhost.databox    | We are connected
driver-os-monitor-store-json.1.yjndtygwa795@localhost.databox    | Timeseries collection created
driver-os-monitor-store-json.1.yjndtygwa795@localhost.databox    | We are connected
driver-os-monitor-store-json.1.yjndtygwa795@localhost.databox    | KV collection created
driver-os-monitor-store-json.1.yjndtygwa795@localhost.databox    | Listening on port 8080
driver-os-monitor-store-json.1.yjndtygwa795@localhost.databox    | [macaroonCache] cashed macaroon not found for syslog/driver-os-monitor-store-jsonPOST requesting one
driver-os-monitor-store-json.1.yjndtygwa795@localhost.databox    | **_[macaroonCache] API Error::  Target syslog has not registered itself for arbitering_**
driver-os-monitor-store-json.1.yjndtygwa795@localhost.databox    | undefined
driver-os-monitor-store-json.1.yjndtygwa795@localhost.databox    | [logging to logstore ERROR] undefined

**Comment by Toshbrown** [comment]
just taking a look at this looks like "syslog has not registered itself for arbitering" is the main issue. 

Syslog is being removed so I might just do that today.

**Comment by tsh-box** [comment]
Thank you for your consideration.

**Comment by Toshbrown** [comment]
I've removed the syslog component, can you try the dev branch and see if it works for you?

**Comment by tsh-box** [comment]
I used the source code from the development branch,and excecuted the startdatabox.sh 
And then I installed the driver-os-monitor but installation does not successfully complete.
Logs are as following :

[databox@localhost databox-development]$ docker service logs driver-os-monitor
driver-os-monitor.1.ikfgt32zt3nf@localhost.databox    | npm info it worked if it ends with ok
driver-os-monitor.1.hadu9hvqnodf@localhost.databox    | npm info it worked if it ends with ok
driver-os-monitor.1.yfy4rieenwun@localhost.databox    | npm info it worked if it ends with ok
driver-os-monitor.1.t1hcatwl2agk@localhost.databox    | npm info it worked if it ends with ok
driver-os-monitor.1.icqan87brc4n@localhost.databox    | npm info it worked if it ends with ok
driver-os-monitor.1.icqan87brc4n@localhost.databox    | npm info using npm@5.3.0
driver-os-monitor.1.ikfgt32zt3nf@localhost.databox    | npm info using npm@5.3.0
driver-os-monitor.1.hadu9hvqnodf@localhost.databox    | npm info using npm@5.3.0
driver-os-monitor.1.yfy4rieenwun@localhost.databox    | npm info using npm@5.3.0
driver-os-monitor.1.t1hcatwl2agk@localhost.databox    | npm info using npm@5.3.0
driver-os-monitor.1.t1hcatwl2agk@localhost.databox    | npm info using node@v8.2.0
driver-os-monitor.1.icqan87brc4n@localhost.databox    | npm info using node@v8.2.0
driver-os-monitor.1.ikfgt32zt3nf@localhost.databox    | npm info using node@v8.2.0
driver-os-monitor.1.hadu9hvqnodf@localhost.databox    | npm info using node@v8.2.0
driver-os-monitor.1.yfy4rieenwun@localhost.databox    | npm info using node@v8.2.0
driver-os-monitor.1.yfy4rieenwun@localhost.databox    | npm info lifecycle driver-os-monitor@0.1.0~prestart: driver-os-monitor@0.1.0
driver-os-monitor.1.t1hcatwl2agk@localhost.databox    | npm info lifecycle driver-os-monitor@0.1.0~prestart: driver-os-monitor@0.1.0
driver-os-monitor.1.icqan87brc4n@localhost.databox    | npm info lifecycle driver-os-monitor@0.1.0~prestart: driver-os-monitor@0.1.0
driver-os-monitor.1.ikfgt32zt3nf@localhost.databox    | 
driver-os-monitor.1.hadu9hvqnodf@localhost.databox    | npm info lifecycle driver-os-monitor@0.1.0~prestart: driver-os-monitor@0.1.0
driver-os-monitor.1.yfy4rieenwun@localhost.databox    | npm info lifecycle driver-os-monitor@0.1.0~start: driver-os-monitor@0.1.0
driver-os-monitor.1.t1hcatwl2agk@localhost.databox    | npm info lifecycle driver-os-monitor@0.1.0~start: driver-os-monitor@0.1.0
driver-os-monitor.1.icqan87brc4n@localhost.databox    | npm info lifecycle driver-os-monitor@0.1.0~start: driver-os-monitor@0.1.0
driver-os-monitor.1.ikfgt32zt3nf@localhost.databox    | > driver-os-monitor@0.1.0 start /
driver-os-monitor.1.hadu9hvqnodf@localhost.databox    | npm info lifecycle driver-os-monitor@0.1.0~start: driver-os-monitor@0.1.0
driver-os-monitor.1.hadu9hvqnodf@localhost.databox    | 
driver-os-monitor.1.yfy4rieenwun@localhost.databox    | 
driver-os-monitor.1.t1hcatwl2agk@localhost.databox    | 
driver-os-monitor.1.icqan87brc4n@localhost.databox    | 
driver-os-monitor.1.ikfgt32zt3nf@localhost.databox    | > node src/main.js
driver-os-monitor.1.ikfgt32zt3nf@localhost.databox    | 
driver-os-monitor.1.hadu9hvqnodf@localhost.databox    | > driver-os-monitor@0.1.0 start /
driver-os-monitor.1.yfy4rieenwun@localhost.databox    | > driver-os-monitor@0.1.0 start /
driver-os-monitor.1.t1hcatwl2agk@localhost.databox    | > driver-os-monitor@0.1.0 start /
driver-os-monitor.1.icqan87brc4n@localhost.databox    | > driver-os-monitor@0.1.0 start /
driver-os-monitor.1.icqan87brc4n@localhost.databox    | > node src/main.js
driver-os-monitor.1.ikfgt32zt3nf@localhost.databox    | npm info lifecycle driver-os-monitor@0.1.0~prestart: driver-os-monitor@0.1.0
driver-os-monitor.1.hadu9hvqnodf@localhost.databox    | > node src/main.js
driver-os-monitor.1.yfy4rieenwun@localhost.databox    | > node src/main.js
driver-os-monitor.1.t1hcatwl2agk@localhost.databox    | > node src/main.js
driver-os-monitor.1.t1hcatwl2agk@localhost.databox    | 
driver-os-monitor.1.icqan87brc4n@localhost.databox    | 
driver-os-monitor.1.ikfgt32zt3nf@localhost.databox    | npm info lifecycle driver-os-monitor@0.1.0~start: driver-os-monitor@0.1.0
driver-os-monitor.1.hadu9hvqnodf@localhost.databox    | 
driver-os-monitor.1.yfy4rieenwun@localhost.databox    | 
driver-os-monitor.1.yfy4rieenwun@localhost.databox    | Target driver-os-monitor-store-json has not registered itself for arbitering
driver-os-monitor.1.t1hcatwl2agk@localhost.databox    | Target driver-os-monitor-store-json has not registered itself for arbitering
driver-os-monitor.1.icqan87brc4n@localhost.databox    | [waitForStoreStatus] Retrying in 1s...
driver-os-monitor.1.ikfgt32zt3nf@localhost.databox    | 1.87451171875
driver-os-monitor.1.hadu9hvqnodf@localhost.databox    | Target driver-os-monitor-store-json has not registered itself for arbitering
driver-os-monitor.1.hadu9hvqnodf@localhost.databox    | [waitForStoreStatus] Retrying in 1s...
driver-os-monitor.1.yfy4rieenwun@localhost.databox    | [waitForStoreStatus] Retrying in 1s...
driver-os-monitor.1.t1hcatwl2agk@localhost.databox    | [waitForStoreStatus] Retrying in 1s...
driver-os-monitor.1.icqan87brc4n@localhost.databox    | Target driver-os-monitor-store-json has not registered itself for arbitering
driver-os-monitor.1.ikfgt32zt3nf@localhost.databox    | Saving data:: loadavg1 1.87451171875
driver-os-monitor.1.ikfgt32zt3nf@localhost.databox    | Saving data:: loadavg5 1.32275390625
driver-os-monitor.1.hadu9hvqnodf@localhost.databox    | [waitForStoreStatus] Retrying in 1s...
driver-os-monitor.1.yfy4rieenwun@localhost.databox    | [waitForStoreStatus] Retrying in 1s...
driver-os-monitor.1.t1hcatwl2agk@localhost.databox    | [waitForStoreStatus] Retrying in 1s...
driver-os-monitor.1.icqan87brc4n@localhost.databox    | [waitForStoreStatus] Retrying in 1s...
driver-os-monitor.1.icqan87brc4n@localhost.databox    | Target driver-os-monitor-store-json has not registered itself for arbitering
driver-os-monitor.1.ikfgt32zt3nf@localhost.databox    | Saving data:: loadavg15 0.78759765625
driver-os-monitor.1.hadu9hvqnodf@localhost.databox    | Target driver-os-monitor-store-json has not registered itself for arbitering
driver-os-monitor.1.yfy4rieenwun@localhost.databox    | Target driver-os-monitor-store-json has not registered itself for arbitering
driver-os-monitor.1.t1hcatwl2agk@localhost.databox    | Target driver-os-monitor-store-json has not registered itself for arbitering
driver-os-monitor.1.t1hcatwl2agk@localhost.databox    | [waitForStoreStatus] Retrying in 1s...
driver-os-monitor.1.icqan87brc4n@localhost.databox    | [waitForStoreStatus] Retrying in 1s...
driver-os-monitor.1.ikfgt32zt3nf@localhost.databox    | Saving data:: freemem 761327616
driver-os-monitor.1.hadu9hvqnodf@localhost.databox    | [waitForStoreStatus] Retrying in 1s...
driver-os-monitor.1.yfy4rieenwun@localhost.databox    | [waitForStoreStatus] Retrying in 1s...
driver-os-monitor.1.yfy4rieenwun@localhost.databox    | Target driver-os-monitor-store-json has not registered itself for arbitering
driver-os-monitor.1.t1hcatwl2agk@localhost.databox    | Target driver-os-monitor-store-json has not registered itself for arbitering
driver-os-monitor.1.icqan87brc4n@localhost.databox    | Target driver-os-monitor-store-json has not registered itself for arbitering
driver-os-monitor.1.ikfgt32zt3nf@localhost.databox    | 2.044921875
driver-os-monitor.1.hadu9hvqnodf@localhost.databox    | Target driver-os-monitor-store-json has not registered itself for arbitering
driver-os-monitor.1.hadu9hvqnodf@localhost.databox    | [waitForStoreStatus] Retrying in 1s...
driver-os-monitor.1.yfy4rieenwun@localhost.databox    | [waitForStoreStatus] Retrying in 1s...
driver-os-monitor.1.t1hcatwl2agk@localhost.databox    | [waitForStoreStatus] Retrying in 1s...
driver-os-monitor.1.icqan87brc4n@localhost.databox    | [waitForStoreStatus] Retrying in 1s...
driver-os-monitor.1.ikfgt32zt3nf@localhost.databox    | Saving data:: loadavg1 2.044921875
driver-os-monitor.1.ikfgt32zt3nf@localhost.databox    | Saving data:: loadavg5 1.3671875
driver-os-monitor.1.hadu9hvqnodf@localhost.databox    | Target driver-os-monitor-store-json has not registered itself for arbitering
driver-os-monitor.1.yfy4rieenwun@localhost.databox    | Target driver-os-monitor-store-json has not registered itself for arbitering
driver-os-monitor.1.t1hcatwl2agk@localhost.databox    | Target driver-os-monitor-store-json has not registered itself for arbitering
driver-os-monitor.1.icqan87brc4n@localhost.databox    | Target driver-os-monitor-store-json has not registered itself for arbitering
driver-os-monitor.1.icqan87brc4n@localhost.databox    | [waitForStoreStatus] Retrying in 1s...
driver-os-monitor.1.ikfgt32zt3nf@localhost.databox    | Saving data:: loadavg15 0.8046875
driver-os-monitor.1.hadu9hvqnodf@localhost.databox    | [waitForStoreStatus] Retrying in 1s...
driver-os-monitor.1.yfy4rieenwun@localhost.databox    | [waitForStoreStatus] Retrying in 1s...
driver-os-monitor.1.t1hcatwl2agk@localhost.databox    | [waitForStoreStatus] Retrying in 1s...
driver-os-monitor.1.t1hcatwl2agk@localhost.databox    | Target driver-os-monitor-store-json has not registered itself for arbitering
driver-os-monitor.1.icqan87brc4n@localhost.databox    | Target driver-os-monitor-store-json has not registered itself for arbitering
driver-os-monitor.1.ikfgt32zt3nf@localhost.databox    | Saving data:: freemem 753872896
driver-os-monitor.1.hadu9hvqnodf@localhost.databox    | Target driver-os-monitor-store-json has not registered itself for arbitering
driver-os-monitor.1.yfy4rieenwun@localhost.databox    | Target driver-os-monitor-store-json has not registered itself for arbitering
driver-os-monitor.1.yfy4rieenwun@localhost.databox    | [waitForStoreStatus] Retrying in 1s...
driver-os-monitor.1.t1hcatwl2agk@localhost.databox    | [waitForStoreStatus] Retrying in 1s...
driver-os-monitor.1.icqan87brc4n@localhost.databox    | [waitForStoreStatus] Retrying in 1s...
driver-os-monitor.1.ikfgt32zt3nf@localhost.databox    | 1.88134765625
driver-os-monitor.1.hadu9hvqnodf@localhost.databox    | [waitForStoreStatus] Retrying in 1s...
driver-os-monitor.1.hadu9hvqnodf@localhost.databox    | Target driver-os-monitor-store-json has not registered itself for arbitering
driver-os-monitor.1.yfy4rieenwun@localhost.databox    | Target driver-os-monitor-store-json has not registered itself for arbitering
driver-os-monitor.1.t1hcatwl2agk@localhost.databox    | Target driver-os-monitor-store-json has not registered itself for arbitering
driver-os-monitor.1.icqan87brc4n@localhost.databox    | Target driver-os-monitor-store-json has not registered itself for arbitering
driver-os-monitor.1.ikfgt32zt3nf@localhost.databox    | Saving data:: loadavg1 1.88134765625
driver-os-monitor.1.ikfgt32zt3nf@localhost.databox    | Saving data:: loadavg5 1.3447265625
driver-os-monitor.1.hadu9hvqnodf@localhost.databox    | [waitForStoreStatus] Retrying in 1s...
driver-os-monitor.1.yfy4rieenwun@localhost.databox    | [waitForStoreStatus] Retrying in 1s...
driver-os-monitor.1.t1hcatwl2agk@localhost.databox    | [waitForStoreStatus] Retrying in 1s...
driver-os-monitor.1.icqan87brc4n@localhost.databox    | [waitForStoreStatus] Retrying in 1s...
driver-os-monitor.1.icqan87brc4n@localhost.databox    | Target driver-os-monitor-store-json has not registered itself for arbitering
driver-os-monitor.1.ikfgt32zt3nf@localhost.databox    | Saving data:: loadavg15 0.80029296875
driver-os-monitor.1.hadu9hvqnodf@localhost.databox    | Target driver-os-monitor-store-json has not registered itself for arbitering
driver-os-monitor.1.yfy4rieenwun@localhost.databox    | Target driver-os-monitor-store-json has not registered itself for arbitering
driver-os-monitor.1.t1hcatwl2agk@localhost.databox    | Target driver-os-monitor-store-json has not registered itself for arbitering
driver-os-monitor.1.t1hcatwl2agk@localhost.databox    | [waitForStoreStatus] Retrying in 1s...
driver-os-monitor.1.icqan87brc4n@localhost.databox    | [waitForStoreStatus] Retrying in 1s...
driver-os-monitor.1.ikfgt32zt3nf@localhost.databox    | Saving data:: freemem 752431104
driver-os-monitor.1.hadu9hvqnodf@localhost.databox    | [waitForStoreStatus] Retrying in 1s...
driver-os-monitor.1.yfy4rieenwun@localhost.databox    | [waitForStoreStatus] Retrying in 1s...
driver-os-monitor.1.yfy4rieenwun@localhost.databox    | Target driver-os-monitor-store-json has not registered itself for arbitering
driver-os-monitor.1.t1hcatwl2agk@localhost.databox    | Target driver-os-monitor-store-json has not registered itself for arbitering
driver-os-monitor.1.icqan87brc4n@localhost.databox    | Target driver-os-monitor-store-json has not registered itself for arbitering
driver-os-monitor.1.hadu9hvqnodf@localhost.databox    | Target driver-os-monitor-store-json has not registered itself for arbitering
driver-os-monitor.1.hadu9hvqnodf@localhost.databox    | [waitForStoreStatus] Retrying in 1s...
driver-os-monitor.1.yfy4rieenwun@localhost.databox    | [waitForStoreStatus] Retrying in 1s...
driver-os-monitor.1.t1hcatwl2agk@localhost.databox    | [waitForStoreStatus] Retrying in 1s...
driver-os-monitor.1.icqan87brc4n@localhost.databox    | [waitForStoreStatus] Retrying in 1s...
driver-os-monitor.1.icqan87brc4n@localhost.databox    | Target driver-os-monitor-store-json has not registered itself for arbitering
driver-os-monitor.1.hadu9hvqnodf@localhost.databox    | Target driver-os-monitor-store-json has not registered itself for arbitering
driver-os-monitor.1.yfy4rieenwun@localhost.databox    | Target driver-os-monitor-store-json has not registered itself for arbitering
driver-os-monitor.1.t1hcatwl2agk@localhost.databox    | Target driver-os-monitor-store-json has not registered itself for arbitering
driver-os-monitor.1.t1hcatwl2agk@localhost.databox    | [waitForStoreStatus] Retrying in 1s...
driver-os-monitor.1.icqan87brc4n@localhost.databox    | [waitForStoreStatus] Retrying in 1s...
driver-os-monitor.1.hadu9hvqnodf@localhost.databox    | [waitForStoreStatus] Retrying in 1s...
driver-os-monitor.1.yfy4rieenwun@localhost.databox    | [waitForStoreStatus] Retrying in 1s...
driver-os-monitor.1.yfy4rieenwun@localhost.databox    | Target driver-os-monitor-store-json has not registered itself for arbitering
driver-os-monitor.1.t1hcatwl2agk@localhost.databox    | Target driver-os-monitor-store-json has not registered itself for arbitering
driver-os-monitor.1.icqan87brc4n@localhost.databox    | Target driver-os-monitor-store-json has not registered itself for arbitering
driver-os-monitor.1.hadu9hvqnodf@localhost.databox    | Target driver-os-monitor-store-json has not registered itself for arbitering
driver-os-monitor.1.hadu9hvqnodf@localhost.databox    | [waitForStoreStatus] Retrying in 1s...
driver-os-monitor.1.yfy4rieenwun@localhost.databox    | [waitForStoreStatus] Retrying in 1s...
driver-os-monitor.1.t1hcatwl2agk@localhost.databox    | [waitForStoreStatus] Retrying in 1s...
driver-os-monitor.1.icqan87brc4n@localhost.databox    | [waitForStoreStatus] Retrying in 1s...
driver-os-monitor.1.icqan87brc4n@localhost.databox    | [ERROR] Target driver-os-monitor-store-json has not registered itself for arbitering
driver-os-monitor.1.hadu9hvqnodf@localhost.databox    | [ERROR] Target driver-os-monitor-store-json has not registered itself for arbitering
driver-os-monitor.1.yfy4rieenwun@localhost.databox    | [ERROR] Target driver-os-monitor-store-json has not registered itself for arbitering
driver-os-monitor.1.t1hcatwl2agk@localhost.databox    | [ERROR] Target driver-os-monitor-store-json has not registered itself for arbitering
driver-os-monitor.1.t1hcatwl2agk@localhost.databox    | Target driver-os-monitor-store-json has not registered itself for arbitering
driver-os-monitor.1.icqan87brc4n@localhost.databox    | Target driver-os-monitor-store-json has not registered itself for arbitering
driver-os-monitor.1.hadu9hvqnodf@localhost.databox    | Target driver-os-monitor-store-json has not registered itself for arbitering
driver-os-monitor.1.yfy4rieenwun@localhost.databox    | Target driver-os-monitor-store-json has not registered itself for arbitering
driver-os-monitor.1.yfy4rieenwun@localhost.databox    | npm info lifecycle driver-os-monitor@0.1.0~poststart: driver-os-monitor@0.1.0
driver-os-monitor.1.t1hcatwl2agk@localhost.databox    | npm info lifecycle driver-os-monitor@0.1.0~poststart: driver-os-monitor@0.1.0
driver-os-monitor.1.icqan87brc4n@localhost.databox    | npm info lifecycle driver-os-monitor@0.1.0~poststart: driver-os-monitor@0.1.0
driver-os-monitor.1.hadu9hvqnodf@localhost.databox    | npm info lifecycle driver-os-monitor@0.1.0~poststart: driver-os-monitor@0.1.0
driver-os-monitor.1.hadu9hvqnodf@localhost.databox    | npm info ok 
driver-os-monitor.1.yfy4rieenwun@localhost.databox    | npm info ok 
driver-os-monitor.1.t1hcatwl2agk@localhost.databox    | npm info ok 
driver-os-monitor.1.icqan87brc4n@localhost.databox    | npm info ok

**Comment by pooyadav** [comment]
For development branch code - please run  the startdatabox script with dev parameter, i.e., startdatabox.sh dev
