### ISSUE TITLE
Cannot see installed App UI and  take a long time

### ISSUE THREAD

**Issue by tsh-box** [me-box/databox#87]
Hello,

I installed app-os-monitor and some logs for app-os-monitor as following 
app-os-monitor.1.ns1c6w000w48@localhost.databox    | Export result:: {"id":"50c24dca-655d-4aeb-bb39-08afc5116f18","state":"Pending","ext_response":{}} <nil>
app-os-monitor.1.ns1c6w000w48@localhost.databox    | DATA::  {"datasource_id":"loadavg5","data":0.916015625,"timestamp":1504770643201,"_id":"59b0fa53ec5e200026b57234"}}
app-os-monitor.1.ns1c6w000w48@localhost.databox    | json.Unmarshal error  invalid character '}' after top-level value
app-os-monitor.1.ns1c6w000w48@localhost.databox    | DATA::  {"datasource_id":"loadavg5","data":0.916015625,"timestamp":1504770643201,"_id":"59b0fa53ec5e200026b57234"}
app-os-monitor.1.ns1c6w000w48@localhost.databox    | DATA::  {"datasource_id":"loadavg15","data":1.3876953125,"timestamp":1504770643201,"_id":"59b0fa53ec5e200026b57235"}
app-os-monitor.1.ns1c6w000w48@localhost.databox    | DATA::  {"datasource_id":"loadavg1","data":0.392578125,"timestamp":1504770648211,"_id":"59b0fa58ec5e200026b57236"}
app-os-monitor.1.ns1c6w000w48@localhost.databox    | DATA::  {"datasource_id":"loadavg5","data":0.90087890625,"timestamp":1504770648216,"_id":"59b0fa58ec5e200026b57238"}}
app-os-monitor.1.ns1c6w000w48@localhost.databox    | json.Unmarshal error  invalid character '}' after top-level value
app-os-monitor.1.ns1c6w000w48@localhost.databox    | DATA::  {"datasource_id":"loadavg5","data":0.90087890625,"timestamp":1504770648216,"_id":"59b0fa58ec5e200026b57238"}
app-os-monitor.1.ns1c6w000w48@localhost.databox    | DATA::  {"datasource_id":"freemem","data":2943598592,"timestamp":1504770648226,"_id":"59b0fa58ec5e200026b57239"}
app-os-monitor.1.ns1c6w000w48@localhost.databox    | Sending  {"id":"","uri":"https://export.amar.io/","data":"{\"datasource_id\":\"freemem\",\"data\":2943598592,\"timestamp\":1504770648226,\"_id\":\"59b0fa58ec5e200026b57239\"}"}
app-os-monitor.1.ns1c6w000w48@localhost.databox    | Export result:: {"id":"90b187e4-77a2-4497-a82d-61f79346e119","state":"Pending","ext_response":{}} <nil>

![screenshot from 2017-09-07 03-40-10](https://user-images.githubusercontent.com/29420329/30193745-0f578dbc-941d-11e7-93de-753db073ed5b.png)

And other UI also cannot see 

![screenshot from 2017-09-07 03-57-31](https://user-images.githubusercontent.com/29420329/30193847-b382c686-941d-11e7-9fea-3442cf891a79.png)

![screenshot from 2017-09-07 03-58-39](https://user-images.githubusercontent.com/29420329/30193870-d10b912e-941d-11e7-8713-55099cbca799.png)

**Comment by Toshbrown** [comment]
I have noticed this issue intermittently, try pressing refresh. 

@ktg can you take a look at this?

**Comment by tsh-box** [comment]
Thanks you ,Now I can see UI by pressing refresh.
And the export service is also work .

![screenshot from 2017-09-07 09-52-58](https://user-images.githubusercontent.com/29420329/30202168-7c783be8-944b-11e7-8516-65d076733d3e.png)

@Toshbrown,Please Could you tell me the way to remote access to the Mongo database of Databox?
I tried to connect to MongoDB but I failed to connect it.

**Comment by Toshbrown** [comment]
@laelaeaung there is no way to access the MongoDB database directly. What are you trying to achieve?

**Comment by tsh-box** [comment]
When joining with PPM server,I want to add the requried table to the Databox 's database.

**Comment by Toshbrown** [comment]
Can you open a new issue that describes in a bit of detail what you are trying to achieve? Then I can advise you on how this could be done whining databox.

**Comment by tsh-box** [comment]
Thanks you very much :)

**Comment by Toshbrown** [comment]
There was an issue with the new golang databox lib exhausting the available TCP connection pool. This eventually caused the container manger to stop responding making the UI appear to hang. This has been fixed in https://github.com/me-box/lib-go-databox/commit/086bf559da6ea2a917fc7dd1f136c14dec6d7e2d
