### ISSUE TITLE
Could you tell me the way to remote access to the Mongo database of Databox?

### ISSUE THREAD

**Issue by tsh-box** [me-box/databox#88]
Hello,
I am trying to connect with Databox and another development project.
In joining process,firstly I need to add the table in  Databox's database.
So how can I access to the mongodb of Databox and add the table(collection) to mongoDB.

**Comment by Toshbrown** [comment]
Databox has many databases (called datastores) there will usually be 1 datastore per driver. 

Accessing the internal database within a datastore is not permitted, it can only be accessed through the exposed API by components within the databox. This is so that authorization, authentication, and logging can be inforced. 

The only way to get data off the box is through the export service. 

Can you explain what the PPM is and what its goals are?

**Comment by tsh-box** [comment]
PPM hold the permission to provide the data(IoT info data) to third user .
The process is 
st1)  Third user request the data(eg;GPS) to Databox
 st2) the Databox accept the request and send this request to PPM server .
 st3) PPM server make authorization about this request and response to the Databox 
 st4) Databox respose to third user with authorization data

**Comment by tsh-box** [comment]
And Is there datastores for per App?

**Comment by Toshbrown** [comment]
Apps can have datastores to, to store processed data and settings.

**Comment by Toshbrown** [comment]
I'm still not sure I have enough information about what you want to achieve.  Do you have any documentation I could take a look at?

**Comment by Toshbrown** [comment]
You should also take a look at this http://dl.acm.org/citation.cfm?doid=3010079.3010082 which describes the databox concept.

**Comment by tsh-box** [comment]
@Toshbrown ,I have no document for it.

![default](https://user-images.githubusercontent.com/29420329/30258425-421bc50e-96f4-11e7-8d57-ee6c72c2c6f9.png)

This is the  process of Databox and PPM.

**Comment by laelaeaung** [comment]
I really want to explain about the details process of PPM.But I can't because this is the confidential information of our project. I am sorry.

**Comment by laelaeaung** [comment]
But could I ask you a question any time?
