### ISSUE TITLE
how can I debug Databox source code

### ISSUE THREAD

**Issue by tsh-box** [me-box/databox#97]
Hello,
Could you please tell me how can I debug the Databox?

Thanks you

**Comment by Toshbrown** [comment]
docker service logs [service name]

Is a good starting point, what are you trying to get working?

**Comment by tsh-box** [comment]
thank you, :)

docker service logs [service name]
Ihave used it.
And I tried to debug the Databox in eclipse,netbeans and visual studio but I failed.
I need to know the databox source code flow .

**Comment by haddadi** [comment]
The software is not written by a single individual in a single IDE, so unlike something like Android, we don't have a single IDE where you can load the whole platform and debug through it. 

The good news is that in anticipation of an upcoming Hackathon*, we will have much better documentation coming, so you shoudl be able to see these appearing soon on the me-box front page over the next few weeks.

* https://www.databoxproject.uk/2017/09/02/databox-hackday-at-mozfest-2017-thu-26-oct/
